_posts/2022-03-15-website-open-source.md

motivation: use correct author name on blog post
changes: update author name to the one listed on the authors list

fix author name on blog post

---

website/index.md

This corrects a small typo in the website overview page.
The author wrote "ash" but meant "as".
I corrected the typo 😇

Tiny typo: ash -> as

---

_layouts/base.html

`og:image`(touch-icon-ipad-180x180.png) does not exist. This change fix it.
`og:image` exist. 
`https://www.swift.org/touch-icon-ipad-180x180.png` ->  `https://www.swift.org/apple-touch-icon-180x180.png`
`og:image` exist.

fix: og:image path

---

_posts/2017-08-22-swift-local-refactoring.md

This pull request corrects a minor typo in the [Swift Local Refactoring](https://www.swift.org/blog/swift-local-refactoring/) blog post.
The author of the blog post spelt "ommitted" incorrectly.
Corrected the spelling.
Old: ommitted
New: omitted

typo fix: ommitted -> omitted

---

assets/stylesheets/_screen.scss

Fix issue "missing overflow style for table contents" (https://github.com/apple/swift-org-website/issues/8).
The missing overflow style for table contents makes some pages layout broken, especially on mobile browsers (or desktop with small window width).
Add attributes `display: block` and `overflow-x: auto` for table content. 
Tested on Safari and the table contents would no longer break pages layout.

fix missing overflow for table contents (#8)

---

_data/builds/swift-5_6-release/amazonlinux2-aarch64.yml
_data/builds/swift-5_6-release/amazonlinux2.yml
_data/builds/swift-5_6-release/centos7.yml
_data/builds/swift-5_6-release/ubuntu1804.yml
_data/builds/swift-5_6-release/ubuntu2004-aarch64.yml
_data/builds/swift-5_6-release/ubuntu2004.yml

Update the Docker links
Make it easier for community to find Docker images

Add Docker links for Swift 5.6

---

source-code/index.md

Add a reference to the Swift.org website source code
Right now, it's somewhat hard to find the Swift.org website repository when browsing `swift.org`
Add a reference to the Swift.org website source code on the `Source Code` page

Add a reference to the Swift.org website source code

---

assets/stylesheets/_screen.scss
assets/stylesheets/core/_reset.scss
continuous-integration/index.md

Fix missing line break for URL and inline code blocks, fix layout for images and blog headers, which makes the website more acceptable on narrow screens.
Currently I found some page of the website seems not fully compatible with narrow screens which cause weird layout issues on some sceneries (eg. viewing on a phone, iPad Spilt-View or browsers with a small window):
1. [https://www.swift.org/download](https://www.swift.org/download) long URLs and inline code blocks makes page layout broken
2. [https://www.swift.org/continuous-integration](https://www.swift.org/continuous-integration) the width of images is consist and not changing with viewport width, I also noticed some missing spacing between texts and images
3. [https://www.swift.org/blog/website-open-source](https://www.swift.org/blog/ …

fix missing line break and refine blog header layout

---

community/index.md
contributing/_contributing-code.md

* <https://bugs.swift.org/browse/SR-7507>
* <rdar://problem/39869728>
https://github.com/apple/swift/pull/14576#issuecomment-366762016
> Technically speaking, the year or years listed are meant to correspond to the year(s) of first publication of the copyrighted work. So if the file was not published in 2014 and didn’t even exist then, we should definitely not be putting that year on the copyright line.
* Remove the `2014 -` from all code templates.
* Update the Swift template to match the standard library.
Apple's lawyers will rejoice.

[SR-7507] Update the code templates

---

assets/stylesheets/_screen.scss

Fix missing overflow style for `blockquote` elements.
The missing overflow style for `blockquote` elements makes some pages layout weird, especially on mobile browsers (or desktop browser with small viewport width).
eg: [https://www.swift.org/blog/package-collections](https://www.swift.org/blog/package-collections/)
Add `overflow-x: auto` to `blockquote` attributes.
Tested on Safari and the pages with `blockquote` elements looks no longer weird.

fix missing overflow style for blockquote

---

download/_windows.md
getting-started/_installing.md
getting-started/_repl.md

Fix some broken or outdated Windows-related documentation.
* Swift on Windows currently explicitly depends on Python 3.7. Reflect
this in our guide.
* Python version 3.7.8 doesn't exist in Windows Package Manager
repository. Point to 3.7.8150.0.
* Windows Package Manager can only install Swift 5.5.3 by the time, which
is obviously outdated.  Recommend Swift.org installers for now.
* Fix Python dependency on Windows to 3.7
* Fix obvious typo in `getting-started/_repl.md`
* Fix incorrect `winget` package version
* Add Swift.org installer guide
More precise guideline for installing and using Swift on Windows.

Fix obvious problems with Windows

---

assets/stylesheets/_mobile.scss

The Swift Logo is not visible on mobile devices
Swift logo is also shown on mobile devices
Before
After

[FIX] Display the Swift Logo on small-width Devices

---

package-manager/_basic-usage.md

Fixed typo and added expected argument to instructions command.
In the referred to dealer project, the name of the executable is "dealer", not "Dealer". Thus typing "swift run Dealer" into the terminal results in an error, which might confuse people.
Also, it would be helpful to include the expected "\<count\>" argument in the instructions (as typing "swift run dealer" alone still results in an error due to the count argument being expected).
Before screenshot: 
After screenshot:

Typo fix: Dealer -> dealer

---

sswg/index.md

Both MQTTNIO and APNSwift packages have been moved to the [swift-server-community](https://github.com/swift-server-community) GitHub organisation. This PR reflects those changes by updating their links on the SSWG page.

Fix SSWG package links after move to swift-server-community

---

download/_older-releases.md

Fix the tag link for swift-5.5.3-RELEASE
The link for the 5.5.3 release tag was wrong (5.3 instead of 5.5.3).
Changed 5.3 to 5.5.3 in the release tag link and description.
The tag will correctly point to 5.5.3

Fix the tag link for swift-5.5.3-RELEASE

---

support/security.md

The cve.mitre.org website has moved over to cve.org
I was browsing the security section, and I clicked on the link to the cve.mitre.org site.  From there, I had to click a second time to get the actual content I was looking for.  The motivation behind this PR is to prevent anyone else from having to click twice :-) 
Updated the CVE-ID link on the support/security to point to the new, preferred URL by the CVE team. 
Anyone clicking that link will get directed to the URL that contains the appropriate content

Updated CVE website URL because it moved

---

platform-support/_platform-support.md

Update the status of SourceKit-LSP on Windows.  It has been available for some time now and works with SPM as on other platforms.

Windows: update SourceKit-LSP status

---

_data/authors.yml
_posts/2022-04-19-sswg-update.md

Add's a blog post for the SSWG's Annual Update

Add SSWG Update

---

quickstart-contribution/index.md

This section used to include a list of selected starter bugs.  That list was removed in #32, as part of the switch from JIRA to GitHub Issues.

Remove into to a list that was already removed.

---

website-governance/index.md

Fix a small typo on the [Swift.org website governance](https://www.swift.org/website-governance/) page.
There is a typo in the text. A similar typo was already fixed in #3, but the same paragraph also existed in another place and was not fixed.
Corrected typo.
No more typos (hopefully)! 🙂 I searched the project and could not find any more typos of this kind at least.

Fix typo: 'ash' -> 'as'

---

community/_forums.md

There is a lack of a space between a dash and the next word, "Automated", in [Community Overview](https://www.swift.org/community).
Minor fix for the typo.

Fix typo in Community Overview

---

mentorship/index.md

This change removes outdated information about the Swift Mentorship Program, including the 2021 timeline and interest surveys.
The Diversity in Swift work group is changing the way interest surveys are submitted, and tweaking the survey questions themselves for the 2022 Swift Mentorship Program. Remove the outdated content until the next round of interest survey submissions is opened to prevent folks from spending time filling out the old survey.
Removes content from the "Current Program" section of Swift.org/mentorship.
The old content is replaced with the guidance to stay tuned to the Announcements category on the Swift Forums.

[Mentorship] Remove outdated mentorship content.

---

website-workgroup/index.md

motivation: share information about the newly formed workgroup
changes: add a section to the website workgroup page with names of members

list website workgroup members

---

_data/navigation.yml

Fix the links in the navigation index for the sections in the Source Code page
The link in the navigation index for the Xcode Playground Support section does not work as the name is not the expected one. There are also a few sections inside the Source Code page that do not have a matching link in the navigation index. These changes fix the link for the Xcode Playground Support section and add the links for the missing sections.
Fix the name for the Xcode Playground Support section to match the right id, and add the sections from the Source Code page that were missing from the navigation index.
All sections inside the Source Code page now have a matching section in the navigation index and they all link to the right section.

Fix navigation links for sections in Source Code page

---

download/_windows.md
getting-started/_installing.md

Change Python Install version for Windows Install dependencies
Python install version is out of date for the current version of Swift
@compnerd I haven't added the change here but I was wondering should we tell the user to open a new terminal after installing the dependencies and before installing swift. I can't be sure but I think that might be required to setup the paths correctly for the swift install.

Fix Python version for Windows install

---

continuous-integration/index.md

These docs provide more detailed info about how to interact with CI.

Add link to CI docs in swift repo

---

_data/authors.yml
_posts/2022-05-19-mentorship-2022.md
mentorship/index.md

Update the community for the 2022 offering of the Swift Mentorship Program with a blog post and updates to Swift.org/mentorship.

[Mentorship] Updates for the 2022 Swift Mentorship Program.

---

_posts/2022-05-19-mentorship-2022.md

This changes the links to be clickable.
It reads better, is easier to use, and is less annoying for VoiceOver to read.
I made the URLs into Markdown links.
The URLs are now clickable.

Updated URLs to be Markdown links.

---

docker-compose.yaml

To avoid broken configs in the future, adding `Jekyll doctor` command. 
https://github.com/apple/swift-org-website/issues/44

Verify Jekyll config in CI

---

assets/stylesheets/_screen.scss

Fix a table width issue caused by PR https://github.com/apple/swift-org-website/pull/11.
In the previous PR, `table { display: block; // ... }` brings some issues to the width of the table elements, thanks for pointed it out https://github.com/apple/swift-org-website/pull/11#discussion_r879027397, so the purpose of this PR is to fix table width issue without revert the previous PR.
Some pages which has this issue:
1. [https://www.swift.org/about/](https://www.swift.org/about/)
2. [https://www.swift.org/download/](https://www.swift.org/download/)
1. For table inside `article`, add another 2 attributes: `width: max-content` and `max-width: 100%`
2. For table inside `details.download`, explicitly use `display: inline-table`
Tested on macOS Safari Version 15.5 (17613.2.7.1.8), the right side …

fix table width issue

---

assets/stylesheets/_screen.scss

Explicitly add `display: list-item` attribute to `<summary>` to fix missing `::marker` on Chrome, Firefox and etc.
Displaying `<summary>` as block leads to missing `::marker` icon in Chrome (Safari is fine) https://github.com/apple/swift-org-website/issues/54, which makes it difficult for users to distinguish what contents can be expanded.
Some pages has the issue:
1. [https://www.swift.org/mentorship/](https://www.swift.org/mentorship/), at "Frequently Asked Questions" part
2. [https://www.swift.org/download/](https://www.swift.org/download/)
Considering this might a bug of Chrome ([ref](https://css-tricks.com/careful-when-changing-the-display-of-summary/)), I would like explicitly add `display: list-item` attribute to `<summary>` in `_screen.scss`, which overrides `display: block` in …

fix missing ::marker of <summary> for Chrome

---

about/_open-source.md

Reverts apple/swift-org-website#57

Revert "Fix broken link for Swift compiler and standard library in about page."

---

about/_open-source.md

To allow time for review, I reverted and re-applied the change.

Fix broken link for Swift compiler and standard library in about page.

---

community/_forums.md

This PR fixes a typo at [/community](https://www.swift.org/community/).
"announcments" -> "announcements"

Fix typo: announcments

---

package-manager/_basic-usage.md

Fix broken anchor link at https://www.swift.org/package-manager/ linking to the **Using the Package Manager** section in https://www.swift.org/getting-started/.
The Package Manager section title in https://www.swift.org/getting-started/ has been changed from "Package Manager" to "Using the Package Manager". Since the title anchors are generated based on the titles, links with anchors to this section also have to be updated.
This PR fixes an outdated anchor link.
- Updated anchor link: `/getting-started#package-manager` -> `/getting-started#using-the-package-manager`
No longer landing at top of the Getting Started page when using this anchor link! :)

Fix broken anchor link

---

_data/preview_packages.yml
standard-library/_preview-package.md

Add missing Standard Library Preview package to the list of current packages.
I noticed that the package list at https://www.swift.org/standard-library/#standard-library-preview-package did not include all packages from [apple/swift-standard-library-preview](https://github.com/apple/swift-standard-library-preview/).
- Added the missing package
- Updated copy
An up-to-date list of current Standard Library Preview packages.

Add missing Standard Library Preview package

---

website-governance/index.md
website/index.md

Some smaller changes to https://www.swift.org/website/ and https://www.swift.org/website-governance/.
I added a link to the `CONTRIBUTING.md` reference that takes you to the file on GitHub. This makes it easier to find and read the guidelines.
I removed two references to the `CODEOWNERS` file, as I thought they were unnecessary. There is already enough information to find out who the maintainers are.
**Note:** We could also link to https://github.com/apple/swift-org-website/blob/main/CODEOWNERS, but I'm not sure if this provides much value (the file is a bit confusing atm as it contains two different lists—maybe we should fix that in a separate PR).
- Added a link to the `CONTRIBUTING.md` reference on /website
- Removed references to the `CODEOWNERS` file
Improved references on …

Improve references on /website and /website-governance

---

mentorship-interest-survey/index.md
mentorship/index.md

Add the Swift Mentorship Program interest surveys, which will open on June 1st at 8am PST through June 26th at 12am PST. This change embeds the survey at a dedicated Swift.org link: https://www.swift.org/mentorship-interest-survey/

[Mentorship] Add the Swift Mentorship Program interest survey.

---

download/_linux.md
download/_older-development-snapshots.md
download/index.md

Support Ubuntu 22.04 
Add latest Ubuntu version
Add links to Ubuntu 22.04 download page.

Add Ubuntu 22.04 support for development snapshots

---

documentation/index.md

The filename includes the Swift language version, so we need to update the link here to match the new content on docs.swift.org.
For rdar://problem/94234377

Update ePub link.

---

documentation/api-design-guidelines/index.md

Migrating the API Design Guidelines from the apple/swift-internals.
Easier to find the content for API Design Guidelines. 
Move index.md file from apple/swift-internals to documentation/api-design-guidelines/index.md

Add API Design Guidelines from apple/swift-internals

---

documentation/api-design-guidelines/index.md

Please see the original PR: https://github.com/apple/swift-internals/pull/30 . Fix a typo in the Swift API Guidelines. This is a doc only change.

Fix typo: "such" -> "such as"

---

_data/navigation.yml

Update sidebar page sections.
I noticed that quite a few pages were missing sections in the sidebar. I added the missing ones.
- updated **About Swift** sections
- updated **Platform Support** sections
- updated **Diversity** sections
- updated **Mentorship** sections
- updated **Continuous Integration** sections
- updated **Source Compatibility** sections
- updated **Security** sections
- updated **Swift on Server** sections
- updated **Swift.org website** sections
(if you want to see which sections were added, the commits below are pretty self-explanatory)
Up-to-date sidebar navigation—makes it easier to get an overview of page contents and to navigate between page sections.

Update sidebar page sections

---

documentation/api-design-guidelines/index.md

Add `#fileID` advice to the documentation.
SE-0285 was [accepted][] (2 years ago).
[accepted]: <https://forums.swift.org/t/accepted-se-0285-ease-the-transition-to-concise-magic-file-strings/38516>
Add the [amendment][] (authored by @beccadax).
[amendment]: <https://github.com/apple/swift-evolution/blob/main/proposals/0285-ease-pound-file-transition.md#swift-api-design-guidelines-amendment>
The [parameters][] section will have a new bullet point.
[parameters]: <https://www.swift.org/documentation/api-design-guidelines/#parameter-names>

[SE-0285] Add `#fileID` to API Design Guidelines

---

download/index.md

Nightly Docker images for Swift 5.7 now available on https://hub.docker.com/r/swiftlang/swift/tags?page=1&name=5.7

Add Docker link to Swift 5.7 nightly snapshots

---

_data/builds/swift-5_6_2-release/amazonlinux2-aarch64.yml
_data/builds/swift-5_6_2-release/amazonlinux2.yml
_data/builds/swift-5_6_2-release/centos7.yml
_data/builds/swift-5_6_2-release/ubuntu1804.yml
_data/builds/swift-5_6_2-release/ubuntu2004-aarch64.yml
_data/builds/swift-5_6_2-release/ubuntu2004.yml

Add links for Swift 5.6.2 Docker images.

Docker images now available on hub.docker.com/_/swift for Swift 5.6.2

---

_posts/2022-03-14-swift-5.6-released.md

Since we merged the Swift-DocC Plugin's getting started guide into the documentation landing page with https://github.com/apple/swift-docc-plugin/pull/9, the link in the Swift 5.6 announcement blog post has been broken.
Fixed the broken link to point to the new page where the plugin's getting started information is located.
The Swift-DocC Plugin documentation link in the Swift 5.6 announcement blog post will work.

Fix broken link to Swift-DocC Plugin docs in Swift 5.6 announcement post

---

_posts/2022-06-21-property-wrappers.md

Fixes grammar issue and title display bug 
Colons in Jekyll titles need to be escaped, but the previous workaround was causing a display issue in Safari. Escaped the title with quotes so that it would display properly.

Fix issues with property wrappers post

---

mentorship/index.md

This change updates the 2022 mentorship timeline. Everything is pushed out by 1 week, and an additional week is added for participants to submit feedback at the end.

[Mentorship] Update the 2022 timeline.

---

README.md

Docker Compose instructions can be confusing as it's not clear you need to build the stack before attempting to run. This PR clarifies that

Clarify the build instructions for Docker

---

website-workgroup/index.md

Reported: https://forums.swift.org/t/swift-website-work-group/57273/12

Fix typo in Tim's name in the Website Workgroup

---

server/guides/allocations.md
server/guides/deploying/digital-ocean.md
server/guides/deploying/gcp.md
server/guides/deploying/ubuntu.md
server/guides/deployment.md
server/guides/index.md
server/guides/linux-perf.md
server/guides/performance.md

Fixes #111.
As these server guide files are not `index.html` files inside a named folder, we have to link to them by appending `.html`.
This is one of probably several ways to fix this, but I think this is good enough for now.
cc: @0xTim

Fix links in Swift Server guides

---

server/guides/deployment.md

added link to AWS Fargate with Vapor and MongoDB guide

---

_layouts/default.html
assets/stylesheets/_screen.scss
download/index.md
index.md

- First pass of updating the content of the landing page.

Update landing page content

---

documentation/index.md

The URL for "The Swift Programming Language" no longer includes the version number in its filename — we need to update the link here to match.

Update ePub link

---

_posts/2022-09-12-swift-5.7-released.md

This proposal is implemented in Swift 5.7 and I missed it in the Swift Evolution Appendix in the release blog post.

Add SE-0363 to the Swift 5.7 evolution appendix.

---

getting-started/_repl.md

Hi, I noticed the REPL instructions no longer work. So I've updated them. Please let me know if there's anything else I should do here.
The REPL is no longer available by simply running `swift`. Now you need to run `swift repl`. Just running `swift` shows help text instead of the REPL as of Swift 5.7:
```
$ swift                                                                             
Welcome to Swift!
Subcommands:
swift build      Build Swift packages
swift package    Create and work on packages
swift run        Run a program from a package
swift test       Run package tests
swift repl       Experiment with Swift code interactively
Use `swift --help` for descriptions of available options and flags.
Use `swift help <subcommand>` for more information about a subcommand.
````
Update the …

Update Getting Started REPL instructions

---

swift-compiler/_compiler-architecture.md

Hello 👋🏻, while reading the [Compiler Architecture page](https://www.swift.org/swift-compiler/#compiler-architecture) I noticed the link texts in the SIL optimizations paragraph did not reflect the actual directory name for the corresponding implementations.
* Fix link texts in SIL optimizations paragraph to reflect the actual implementation directory names.
* Changed the casing of the compiler component names in the last two paragraphs to use sentence case, as in the paragraphs  above them—for consistency sake. 
Screenshot of content after changes:

Fix link texts in Compiler Architecture page

---

sswg/index.md

Follow up to https://github.com/apple/swift-org-website/pull/143
Since we also have to update the list of projects to include the newly accepted ones

[sswg] Update the listing website for graphql

---

sswg/index.md

Oh boy, pasting in github made a weird syntax error I didn't notice... Fixing the links.

[sswg] Fix link syntax

---

_layouts/base.html
assets/stylesheets/_screen.scss

Staging header will only display if `JEKYLL_ENV=stage` set. 
**For example:** 
```
JEKYLL_ENV=stage LC_ALL=en_us.UTF-8 bundle exec jekyll serve
```
**Screenshot:**

Add staging header across the website

---

_data/navigation.yml

All other swift workgroup's post is listed under "Open Source Efforts". Swift Documentation Workgroup should be listed here too. (Now it can only be discovered by the Announcement Post)
https://www.swift.org/documentation-workgroup/
Add "Swift Documentation Workgroup" Page to the Navigation Bar
"Documentation Workgroup" will be added under "[C++ INTEROPERABILITY](https://www.swift.org/cxx-interop-workgroup/)"

Add Documentation Workgroup to navigation

---

community/index.md

After #32 , we update the bug track link to Github Issues.
And since swift-org-website is open sourced too. Maybe "the Swift.org bug tracking system" should be redirected to this repo instead of apple/swift repo.

Update name of bugtracker

---

documentation/api-design-guidelines/index.md

Developers unfamiliar with the use of "iff" as an abbreviation for "if and only if" are confused and file bugs, both against this page and against reference for the Swift standard library, because it looks like a typo.
This PR re-creates <https://github.com/apple/swift-internals/pull/20>, which was closed during the Git repository move.  For an example of real documentation with and without "iff", see <https://github.com/apple/swift/pull/39977>.
Fixes rdar://56670458

Replace "iff" in API guidelines

---

documentation-workgroup/index.md

Issus on documentation and documentation tooling enhancements and bugs should better be reported at `apple/swift-docc` rather than `apple/swift`. cc @franklinsch 
Update the Github issue link on Swift Documentation Workgroup Chapter.
The Github issue link on Swift Documentation Workgroup Chapter will be redirected into https://github.com/apple/swift-docc/issues

Update issue link from swift to swift-docc

---

mentorship/index.md

The StartBug link is broken
Change link style from Markdown style to HTML
- Before: https://www.swift.org/mentorship/#frequently-asked-questions
- After: http://127.0.0.1:4000/mentorship/#frequently-asked-questions

Fix StartBug link in Mentorship Page

---

documentation-workgroup/index.md

[language-workgroup](https://www.swift.org/language-workgroup/) lists their members with link support so that others could easily reach out to them. 
IMO, add such links in Documentation Workgroup would be great.
Forum discussion link https://forums.swift.org/t/website-add-member-links-for-documentation-workgroup-page/60732 (Private for Documentation Workgroup member)
The PR adds Github link for each of the Documentation Workgroup member.
If the link is wrong, feel free to reach to me or comment on the PR.
Before
After

Add Github link for Documentation Workgroup member

---

contributing/_reporting-bugs.md

* Remove a mention of Jira.
* Urge reporters to pay extra attention to whether their test case reproduces the issue. We’d rather spend time fixing issues than completing test cases to reveal them.
* Bump the estimate of a small test case from "less than 20" to "within 50" lines of code. 50 lines is *fine* for an inline sample—stack traces are often commensurate, yet we tend to prefer them inline.
* Encourage reporters to reduce their test cases. Reduced examples are far easier to debug and more future-proof.
* Use "open" instead of "file" in relation to a GitHub issue.
* Prefer "version information" over the somewhat cryptic "Swift build number".
* Prefer the more familiar "deployment target" over "target OS" as per Xcode’s nomenclature.

contributing: Minor amendments and additions to bug reporting guidelines

---

_includes/linux/table.html
_includes/linux/ubuntu2204.html

[Getting Started page](https://www.swift.org/getting-started/) does not list dependencies for Ubuntu 22.04, even though this version is supported.
Added a list of packages, as listed [in the corresponding `Dockerfile`](https://github.com/apple/swift-docker/blob/main/5.7/ubuntu/22.04/Dockerfile).
Now it should be easier for users of Ubuntu 22.04 to install Swift.

_includes/linux: list dependencies for Ubuntu 22.04

---

contributing/_answering-questions.md

It looks like this link was missed during the switch from mailing lists to forums. The page still exists, but the anchor has gone so the visitor was left at the top of the community page.

Fixed an old mailing list link

---

getting-started/_build-system.md

We have a getting started guide for using package plugins on the SwiftPM repo and it would be good to link it from swift.org

Add reference to plugin getting started guide

---

assets/stylesheets/_screen.scss

Resolves #178
Fixes the visibility of "More Detail" and "Less Detail" controls in Firefox. ([forums post](https://forums.swift.org/t/can-t-expand-html-sections-in-api-design-guidelines/))
"More Detail" and "Less Detail" controls were missing from Firefox. They were visible in Safari and Chrome.
Adds `-moz-appearance: none;` to `article input.detail[type=checkbox]`. 
"More Detail" and "Less Detail" controls are now visible in Firefox.
**Before:** 
**After:**

Fix visibility of detail controls in Firefox.

---

_data/builds/swift-5_7_1-release/amazonlinux2-aarch64.yml
_data/builds/swift-5_7_1-release/amazonlinux2.yml
_data/builds/swift-5_7_2-release/amazonlinux2-aarch64.yml
_data/builds/swift-5_7_2-release/amazonlinux2.yml
_data/builds/swift-5_7_2-release/centos7.yml
_data/builds/swift-5_7_2-release/ubuntu1804.yml
_data/builds/swift-5_7_2-release/ubuntu2004-aarch64.yml
_data/builds/swift-5_7_2-release/ubuntu2004.yml
_data/builds/swift-5_7_2-release/ubuntu2204-aarch64.yml
_data/builds/swift-5_7_2-release/ubuntu2204.yml

The docker images are now available on hub.docker.com, adding the links for them on download page.

Add links to Swift 5.7.2 Docker images

---

_posts/2022-12-09-future-of-foundation.md

The use of `post_url` in the “The Future of Foundation” blog post was causing a Jekyll warning:
```
Generating... 
Deprecation: A call to '{% post_url /blog/2015-12-03-welcome %}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
```
This PR fixes the warning.

Fix Jekyll warning in the “The Future of Foundation” blog post

---

_data/go_further.yml

Add data file with items for _Go Further_ section of _Getting Started_ page.
This PR is against the `content-improvements` branch.
As discussed in previous workgroup meetings, here is the initial pass at data for items for the Go Further section.
Note that the thumbnail URLs are TBD but included as placeholder entries.

Add data file with items for "Go Further" section

---

assets/stylesheets/pages/_swift-evolution.scss

Search field on the Swift Evolution page has default user agent style applied, which makes it too small and close to unreadable on Safari. In other browsers the field does not fit with the website style, as it has no border radius and also has inconsistent position.
*Before:*
*After:*
*Before:*
*After:*
*Before:*
*After:*
Search field on the Swift Evolution page is readable and fits the overall website design in all browsers.

swift-evolution: update search text input

---

_includes/getting-started/_installing.md
getting-started/_use-cases.html
getting-started/cli-swiftpm/index.md
getting-started/cli-tool/index.md
getting-started/index.md
getting-started/library-swiftpm/index.md
getting-started/library/index.md

motivation: getting started guides
changes:
* add a cli guide
* add a library guide + link from index page
* share install instructions across pages

add cli and library getting started guides

---

CONTRIBUTING.md
_data/navigation.yml
blog-post-contributions/index.md
contributing/_website-and-blog-post-contributions.md
contributing/index.md
website-governance/index.md

This change supports the [Swift Website Workgroup](https://www.swift.org/website-workgroup/)'s goal of encouraging more community contribution to the Swift.org website and blog.
Here is a first draft of the potential changes to the community blog post contribution process.
All suggestions are welcome on anything in this PR. I’d also welcome an official eye on whether any of my changes to the governance process are suitable. I did consider adding the submission process directly in to the governance page, but it’s already quite long.
I think I managed to catch everywhere that the site talks about blog post contributions and redirect them into the new process, but please let me know if I missed any.
Thanks also to @alexandersandberg for his help with creating this process.

Community blog post submission process changes

---

assets/stylesheets/pages/_swift-evolution.scss

Follow-up to apple/swift-org-website#198.
The search-bar was recently changed to use a fixed height, which is a rendering issue when the filter-options are expanded.
Use `min-height` instead of `height`.
* Before (with `height`):
* After (with `min-height`):

[SE Dashboard] Update the search-bar height style

---

_includes/getting-started/_installing.md
getting-started/_use-cases.html
package-manager/index.md

Improving the Getting Started page from the perspective of someone completely new to Swift.
* Removed the references to `swift build`, `swift test`, `swift run`. If someone had just installed Swift to the point where they can run `swift --version` as recommended on the lines above, these commands are going to fail while looking for `Package.swift`. The use case examples below introduce these commands in a more natural way.
* Tweaked how we introduce the SwiftPM abbreviation when we first introduce it (and also on the package manager page).
* Link to the package manager page when introducing SwiftPM.
* Added a link to TSPL. I know we want to get into some slightly less daunting tasks than "Read this whole book", but I feel it's important to have a link to it somewhere on this page. I tried …

Getting started tweaks

---

_data/builds/swift-5_7_3-release/amazonlinux2-aarch64.yml
_data/builds/swift-5_7_3-release/amazonlinux2.yml
_data/builds/swift-5_7_3-release/centos7.yml
_data/builds/swift-5_7_3-release/ubuntu1804.yml
_data/builds/swift-5_7_3-release/ubuntu2004-aarch64.yml
_data/builds/swift-5_7_3-release/ubuntu2004.yml
_data/builds/swift-5_7_3-release/ubuntu2204-aarch64.yml
_data/builds/swift-5_7_3-release/ubuntu2204.yml

Docker images are now available on hub.docker.com/_/swift

Update the Docker image links for Swift 5.7.3

---

_data/go_further.yml
assets/stylesheets/pages/_getting-started.scss
getting-started/_go-further.md
getting-started/_use-cases.md

Improving the layout of the getting started page in the light of the new content updates.
- Updated link to SwiftUI guide.
- Sourced Go Further section from the data file.
- CSS changes to the sections.
[Preview link](https://swift-org-website-kaishin.vercel.app/getting-started/)

Update getting started page layout

---

swift-compiler/_compiler-architecture.md

`The parser [...] emit warnings` -> `The parser [...] emits warnings`
Resolves https://github.com/apple/swift-org-website/issues/222.

swift-compiler/_compiler-architecture.md: fix typo

---

gsoc2023/index.md

Preparing for GSoC 2023 🎉 
The page is empty for now. We'll announce projects and how to add ideas very soon.
We should merge this even while empty, so we can use the link during the GSoC application.

Prepare GSoC23 projects page

---

_data/sswg/projects.yml
sswg/index.md

I [noticed recently](https://github.com/apple/swift-org-website/pull/231#issuecomment-1413283423) that the projects table on the Swift on Server page was using a static table instead of the existing (but outdated) projects data file.
Using a data file will make the process of maintaining this list easier.
- Updated the `_data/swwg/projects.yml` file to match the static table on the Swift on Server page
- Replaced the static table with one generated from the data file
Note: The date format is now changed from MM/DD/YYYY to YYYY-MM-DD (05/16/2019 → 2019-05-16). As we've had some issues with the former before (mixing up days and months), I think this more internationally recognized date format is better.
The same table as before but now generated from the data file. When SSWG now wants to …

Generate Projects list on Swift on Server page with data file

---

download/index.md

Universal Base Image 9 for AArch64 now available for `main` branch.

[Download] Add support for UBI 9 AArch64

---

gsoc2023/index.md

Fixed a small typo in the index.md file where the year 2022 was mistakenly written instead of 2023 while mentioning the tag for the gsoc program. The corrected year has been updated in the file.
This change will ensure that the index.md file accurately reflects the correct date, improving the overall accuracy and readability for the potential contributors on the site.
Changed two occurrences of `gsoc2022` tag with `gsoc2023` tag in the [gsoc/index.md](https://github.com/apple/swift-org-website/blob/main/gsoc2023/index.md) file
Correct information about the program will be displayed.

Fixed typographical error on /gsoc/2023.md

---

getting-started/index.md
package-manager/index.md

Before this change, the link went through multiple redirects:
* https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/GuidedTour.html#//apple_ref/doc/uid/TP40014097-CH2-ID1
* https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/GuidedTour.html
* https://docs.swift.org/swift-book/GuidedTour/GuidedTour.html
* https://docs.swift.org/swift-book/documentation/the-swift-programming-language/guidedtour/
The redirects are themselves undesirable, and some users are getting 404 errors from the last redirect getting confused.  (I'll look into that issue next, separately.)
Note that the link from the SwiftPM page goes to the top level, because the prose around it is referring to the book in …

Update links to TSPL, to avoid multiple redirects

---

_data/go_further.yml
documentation/index.md
getting-started/_use-cases.md
getting-started/vapor-web-server/index.md
index.md

motivation: address feedback from content review
changes:
* slight langauge changes
* update vapor guide to be more generic so that we an also point to other web frameworks in the future

update content-improvments branch per feedback

---

assets/stylesheets/_pages.scss
assets/stylesheets/pages/_landing.scss
index.md

As discussed in the latest SWWG meeting, we should make some improvements to the new landing page content. I have started here with the 'Why Swift?' section.
- Shortened the Safe, Fast, and Expressive texts and turned them into cards
- Added a link to /about to learn more about Swift
|Desktop|Mobile|
|---|---|
|<img width="985" alt="CleanShot 2023-03-06 at 09 12 27" src="https://user-images.githubusercontent.com/35671299/223053705-e16ba09b-92dd-48c2-8ee1-61f17c21b82c.png">|<img width="470" alt="CleanShot 2023-03-06 at 09 13 51" src="https://user-images.githubusercontent.com/35671299/223053987-65762864-62c9-4c64-971d-44f5938ee6fe.png">|

Improve landing page

---

_data/go_further.yml

Based on feedback from the core team, this replaces the more advanced topic "String Under The Hood" with a Go Further entry about the type system.
Most WWDC sessions from Swift's early days that cover these concepts are no longer available and have outdated code examples that are no longer valid Swift or assume significant knowledge of UIKit which is not suitable for a general Swift audience.
The best existing swift.org or Apple resource for this topic that I could identify is the _Structure and Classes_ chapter of _The Swift Programming Language_.

Replace Go Further strings item with item about types (structures and classes)

---

download/_windows.md
getting-started/_installing.md

I wanted to add scoop installation methods for swift, since I am the one who added it to [scoop](https://scoop.sh/).
I added scoop installation methods to these files, **getting-started/_installing.md** and the **download/_windows.md**
**getting-started/_installing.md** and **download/_windows.md** will now have sections that detail how to install the dependencies and the Swift programming language using scoop.

Add Scoop installation methods for Windows

---

gsoc2023/index.md

Updating project description since binary protocol is deprecated. 
As per discussed here: https://forums.swift.org/t/interested-in-memcached-client-project/63549/5
Fixes: #255

Update memcached client project details

---

gsoc2023/index.md

This adds a GSoC 2023 project idea for Swift-DocC localization support
The Swift-DocC team would like to propose a project idea for GSoC 2023 
Updates the GSoC 2023 "Potential Projects" list to include a Swift-DocC project idea.
The Swift-DocC localization support project idea will be listed among the GSoC 2023 "Potential Projects".

[GSoC23] Add project idea for Swift-DocC localization support

---

gsoc2023/index.md

Fix project heading levels.
Heading levels in a couple of projects were `h3` instead of `h4`.
Use `h4` for "Scripting in Swift" and "Memcached Client".

Fix project heading levels in GSoC 23 page

---

download/index.md

The warning about experimental RPMs is for 5.7.2, but we've released 5.7.3.  We should either update the version (as done here), or move the warning under the older releases disclosure for 5.x if it really is specific to 5.7.2.

[downloads] Update 5.7.2 -> 5.7.3 in RPM warning

---

_layouts/post.html
assets/stylesheets/_screen.scss

This PR contains three small commits that address a few issues in how authors are presented in blog posts. Each change has been tested in a desktop browser and a mobile-sized browser.
Currently the first author's name is listed next to the date of the blog post. This looks very awkward and unaligned when there are multiple authors:
_Example 1:_
---
_Example 2:_
---
This change puts the first author below the date in all cases, which is consistent between all blog posts and makes multi-author posts look much better:
_Updated Example 1:_
---
_Updated Example 2:_
---
Note that in the commit, bottom padding and margin values were adjusted to maintain spacing between the heading and the body of the post. These CSS values also affect the main blog listing. In both cases, the spacing between the …

Cleanup blog author layout

---

contributing/_llvm.md

LLVM Bugzilla is read-only and represents the historical archive of all LLVM issues filled before November 26, 2021. We should use a link to GitHub to point to the actual LLVM bug tracker.

Update LLVM bug tracker link in `contributing/_llvm.md`

---

_posts/2023-03-30-swift-5.8-released.md

- The proposal is now listed as being implemented in 5.9
There was some back and forth over this issue in the original post PR.
The proposal is now listed on the evolution page as implemented in 5.9, so it should be removed from the Swift 5.8 post.
Here is the link to the proposal: https://www.swift.org/swift-evolution/#?proposal=SE-0374

Remove SE-0374 from Swift 5.8 post

---

_data/builds/swift-5_8-release/amazonlinux2-aarch64.yml
_data/builds/swift-5_8-release/amazonlinux2.yml
_data/builds/swift-5_8-release/centos7.yml
_data/builds/swift-5_8-release/ubi9-aarch64.yml
_data/builds/swift-5_8-release/ubi9.yml
_data/builds/swift-5_8-release/ubuntu1804.yml
_data/builds/swift-5_8-release/ubuntu2004-aarch64.yml
_data/builds/swift-5_8-release/ubuntu2004.yml
_data/builds/swift-5_8-release/ubuntu2204-aarch64.yml
_data/builds/swift-5_8-release/ubuntu2204.yml

The Swift 5.8 Docker images are now available on hub.docker.com.

Add Swift 5.8 Docker image links to download page

---

_posts/2023-03-30-swift-5.8-released.md

Fixes a typo the upcoming feature flag for regex literals in the 5.8 blog post.
FYI, I noticed the typo by copying flag out of the blog post and into Xcode to try out the new 'upcoming feature' functionality. I would guess other readers might do the same leading to confusion.

Fix typo in the 'BareSlashRegexLiterals' upcoming feature flag in 5.8 blog post

---

download/index.md

* "RPM" now belongs to "Swift 5.8" instead of being on the same level. 
* Using headlines instead of emphasis for "Amazon Linux 2" and "CentOS 7" is generally advised.

Use headlines with correct level instead of emphasis

---

assets/javascripts/swift-evolution.js

- Read and display `upcomingFeatureFlag` field if present
- Enable search on that field
- Use a map between proposal id and upcoming feature flags temporarily until backing JSON file adds the `upcomingFeatureFlag` field.
- Part of Issue #261 
This PR adds support for an 'upcoming feature flag' field to be read, displayed, and searched on the Swift Evolution page.
Note that the `upcomingFeatureFlag` field is not present in the source `proposals.json` file at the moment. This PR uses a map from proposal id to upcoming feature flag in the JavaScript file to add the property to the appropriate proposals. This is intended to be temporary until the property is included in the JSON.
Note also that this Issue #261 also includes filtering for all proposals with an upcoming feature flag. This PR …

Add support for feature identifier field on Swift Evolution page

---

atom.xml

Fix the [atom feed](https://www.swift.org/atom.xml) so it sorts by updated date in descending order and limits entries to 20.
The current atom feed is sorted in ascending order and includes all entries. Since each entry has a `<content>` node the file ends up being 427 kb gzipped.
The sort issue happens because the sort key is `date` and not `updated`. Entries have an `updated` node, not a `date` node.
The limit happens because [limit](https://shopify.github.io/liquid/tags/iteration/#limit) should be applied in the `for` loop and not the variable assignment in the tag.
Changed the sort key from `date` to `updated` and applied `limit` in the `for` loop.
Entries are sorted in descending order and limited to 20.
Jekyll's dev server doesn't gzip the file, so I downloaded it and gzipped it. …

Fix atom feed sort and limit

---

assets/javascripts/swift-evolution.js
assets/stylesheets/pages/_swift-evolution.scss
swift-evolution/_dashboard.html

This PR implements a dedicated filter button for proposals with an upcoming feature flag as described in Issue #261.
From my testing everything is working as intended. The feature flag filter correctly interacts with the status/version filter. The per-status count values update correctly. The URL fragment that includes the search/filter settings now includes the feature flag filter state and is read and written as expected.
I have tested with multiple iOS devices and the tap targets of the filter buttons seem to be large enough to tap each easily.
- Add click handler to flag filter button
- Add method that filters out proposals without a UFF
- Add a URL that links to info about upcoming feature flags
- Add suffix to status string 'with upcoming feature flags'
- Include link to info about …

Upcoming feature flag filter

---

_data/go_further.yml

- Use latest URL for Swift tour in TSPL
- Reorder items
- Add title and blurb for Value and Reference Types blog post
Note that the Value and Reference Types blog post is still awaiting internal approval so is not in a PR yet. Adding title and blurb for it to show the intended content for the demo.

Update Go Further section

---

assets/javascripts/swift-evolution.js

The _Using Upcoming Feature Flag_ post on Swift.org serves as an introduction and practical guide to using upcoming feature flags.
The existing link is to the evolution proposal for the feature which is a design document.
This PR updates the link to point to the post, to better support users learning about and using upcoming feature flags found on the evolution dashboard.

Update evolution page link to point to 'upcoming feature flag' post.

---

platform-support/_platform-support.md

Starting Swift 5.8 the min deployment has been updated
```
DARWIN_DEPLOYMENT_VERSION_OSX = '10.13'
DARWIN_DEPLOYMENT_VERSION_IOS = '11.0'
DARWIN_DEPLOYMENT_VERSION_TVOS = '11.0'
DARWIN_DEPLOYMENT_VERSION_WATCHOS = '4.0'
```

Update the minimum deployment version

---

server/guides/setup-and-ide-alternatives.md

JetBrains has sunset its Swift support for CLion.
https://plugins.jetbrains.com/plugin/8240-swift
remove CLion because JetBrains is no longer supporting Swift
Documentation for CLion Swift support is out of date and can be confusing for people who want to write Swift on other platforms.
I removed the line referencing CLion.
CLion will no longer be on the list of IDEs/Editors with Swift Support

remove CLion because JetBrains is no longer supporting Swift

---

assets/stylesheets/pages/_getting-started.scss
assets/stylesheets/pages/_landing.scss
getting-started/_use-cases.md
index.md

motivation: address feedback frmo core-team
changes:
* improve description of landing page use cases
* improve description of getting started guides
* add "cross platform command-line tool" as a landing page use case
* change link of use cases to their relevant getting started guides

improve description of use cases and getting started guides

---

_data/featured_snippets.yml
assets/stylesheets/pages/_landing.scss
index.md

Adds proof of concept for dynamic code snippet on the landing page.
This is a proof of concept for featuring a random code snippet on the landing page. Whether we want to add dynamic content to the landing page or not is a separate discussion, but with this, we can preview what it would be like.
The snippets are stored in `_data/featured_snippets.yml`. For this POC, I used some random snippets from TSPL. If/when implementing this, we would use some better, more representative snippets.
I now render all snippets in the HTML and hide them all except for the first one with CSS. This allows the syntax highlighter to find and highlight all snippets. I found this to be the best and easier way of doing this. Other possible ways might involve preprocessing the data file to add syntax highlighting …

POC: Feature random code snippet on landing page

---

diversity/index.md

This removes my name from the list of Diversity in Swift workgroup members.
I had a great time working on the Diversity in Swift workgroup, and I am very grateful to the other members of the group for doing such a great job launching and supporting a range of initiatives. However, my two-year term has passed and I have now left the workgroup.
Given that the role of Swift workgroups is evolving (https://www.swift.org/blog/evolving-swift-project-workgroups/) this page may need further changes, but I'll leave that to folks who are more in the know.

Removing Paul Hudson from Diversity in Swift

---

documentation-workgroup/index.md

"Kelvin Ma" has changed the Github ID from "kelvin13" to "tayloraswift"
The old link will point to a 404 page instead of redirecting to homepage with the new ID.
cc @tayloraswift 
Update outdated Github link
Fix the Github link.

Update outdated GitHub link

---

download/_older-releases.md

On the downloads page, the older release 5.8 is mislabeled as 5.7.3.
Fix the heading text.
The heading will reflect the right version: 5.8.

download page: fix mis-labeled older 5.8 release

---

_data/navigation.yml

motivation: clearer navigation structure
changes:
* remove "Open Source Development" and " "Open Source Efforts" sections
* create new "Documentation" section and move compiler, stdlibe, swiftpm and other docs previsouly under "Open Source Efforts" to this section
* move workgroup links from "Open Source Efforts" section to "Community" section
* create new "Governance" section and move CoC and security policy links to this section

re-arrange main navigation

---

about/index.md
assets/stylesheets/pages/_landing.scss
index.md

During the last meeting, we discussed having a `h1` with “Safe, Fast, Modern“ above the “Swift is…“ copy here, but after playing with it, I don’t think that feels quite right.
I’d be happy to change it if the consensus is to have that strong three-word lead-in, but it didn’t feel quite right to me.
This is what felt best to me:
Then I also tackled the "Safe, Fast, Expressive" section that begins the "About" page as I think they should line up. This copy *definitely* needs work, this is just a first draft. Let's discuss in this PR.

New “Swift is…” and About page copy

---

_data/go_further.yml
assets/stylesheets/pages/_getting-started.scss
getting-started/_use-cases.md

We discussed trying out this direction during a a recent feedback session.
- Removed "A Swift Tour" from the Go Further section.
- Added a new "New to programming?" section in the Use cases section.
- Moved down the link to TSPL so that it comes after the use cases (we didn't consider this option during the meeting, but I think it looks better in terms of both flow and layout).

[Content Improvements] Move link to A Swift Tour to the Use Cases section

---

_data/navigation.yml
community/index.md
legal/license.md

motivation: highlight license as part of the project governance
changes:
* create a new page for license information
* extract information from community overview page into the new license page
* create navigation entry under governance to the new license page

extract the license information from the community overview into its own page

---

assets/javascripts/swift-evolution.js

Add an entry to the `upcomingFeatureFlags` map.
SE-0401 has been accepted and implemented (Swift 5.9).
Update the "swift-evolution.js" file.
SE-0401 will be included in the <https://www.swift.org/swift-evolution/#?upcoming=true> filter.

[SE-0401] DisableOutwardActorInference (dashboard)

---

_posts/2023-05-30-using-upcoming-feature-flags.md

Code samples shouldn't have smart quotes in them. Not only this breaks syntax highlighting, but won't build when pasted into actual source code.

Upcoming Features Blog Post: avoid smart quotes in code samples

---

getting-started/cli-swiftpm/index.md
getting-started/library-swiftpm/index.md
getting-started/swiftui/index.md
getting-started/vapor-web-server/index.md

As discussed, this adds a consistent download section to the start and end of each guide

Add consistent download section to start and end of each guide

---

_posts/2023-08-17-sswg-update-2023.md

Update a single sentence in today's SSWG blog post to avoid implying 2023 is just starting.

Minor sentence tweak to avoid implying 2023 is just starting

---

getting-started/cli-swiftpm/index.md
getting-started/library-swiftpm/index.md

motivation: finalize the getting started guides
changes:
* use default bash prompt
* update url + name of example library used in cli guide
* fix small typos

[content improvements] update cli and library getting started guides

---

download/_windows.md
getting-started/_installing.md

The Windows installation process errored out on my PC, complaining that `start` could not find the `vs_community.exe` file, which was however present after running `ls`. 
- Change the installation code block for Windows to not use `start`, but instead execute the installer directly.
- Change the reference to the Microsoft Store from "App Store".
The installation instructions for Windows have changed to 
a) not quit with an error
b) correctly reference the Microsoft Store

Change Windows installation instructions

---

documentation/cxx-interop/index.md

index is not part of the URL, causing server to respond 404 error code.

Fix bad links

---

getting-started/cli-swiftpm/index.md
getting-started/library-swiftpm/index.md

Updates the guides so they match what's generated for 5.8 to avoid confusion
cc @tomerd

Content improvement guide updates

---

_posts/2023-08-29-swift-5.9-released.md

Add some words about the new crash handler, including a promise of a future blog post on the subject.

Add a Crash Handling subsection.

---

_data/go_further.yml
assets/stylesheets/_screen.scss
documentation/articles/value-and-reference-types.md

- Update link from Go Further section of Getting Started page
- Add a bit of CSS to display author info correctly.
Should probably move to an ‘article’ layout that encapsulates this.

Add value and reference types article

---

_data/builds/swift_releases.yml
download/_build-platform.html

This PR proposes a solution to links for Red Hats download links being broken due to a mismatch between the logic constructing the URL and the actual URL.

Resolve issue with Red Hat download links

---

_posts/2023-08-29-swift-5.9-released.md

Remove the line promising a future blog post (I'd still like to do one).

Remove promise of a future blog post.

---

assets/stylesheets/pages/_landing.scss
getting-started/_go-further.md

This PR fixes the mobile layout of the use cases section in the landing page.
- Make the children grid properties only applicable within the large viewport media query.

Fix mobile layout of use cases section

---

_data/go_further.yml

Fixes the link on the homepage for the Value And Reference Types In Swift article

Fix broken link on homepage

---

platform-support/_platform-support.md

* Include Red Hat Universal Base Image as supported platform and the minimum deployment version (9)
* Windows testing is now required in pull request before changes can be merged.
https://github.com/apple/swift-org-website/issues/380

Update the Platform Support page

---

download/_build-platform.html

Fixed aarch64 download links for the current stable release.
Currently the `x86_64` and `aarch64` downloads for the current release point both to the `x86_64` download artifact for the release.
Added a condition in the download template which appends the arch to the url if it's not the default `x86_64`
Download links for `aarch64` will point to `aarch64` downlaod artifacts and `x86_64` to the `x86_64` ones.

Fix #394, aarch64 download links broken

---

_posts/2018-01-19-forums.md

I was working on #369 and looking for an announcement of Swift Forums launch, so that I could replace links to Swift Mailing lists, and add a little snippet on why that change was made. 
Found the post — it was slightly broken, so I thought I'd fix it while I'm here.
Uh, well, I slammed the space bar five times. I'm shy to even blast the email notification about this pull request because of how small this change is, but hey. Since this change is not directly related to the link URL checker, it goes into it's own little PR.
| Before | After|
|--------|------|
| <img width="1612" alt="Screenshot 2023-09-14 at 9 33 29 PM" src="https://github.com/apple/swift-org-website/assets/43633/ac645f3c-6c53-4630-8c10-b99bddfa8c1c"> | <img width="1612" alt="Screenshot 2023-09-14 at 9 34 19 PM" …

Fixed header markup in /blog/forums

---

download/_build-platform.html

Fixes the links in downloads > older releases blocks in `download/_build-platform.html`. The links used markdown syntax in a html file, and hence would not render correctly.
The first block of footnotes on the page rendered correctly, only the "Older releases" were broken. I've only spotted them because some of the Xcode download links were broken.
After/before:

Fix download footnotes links

---

_posts/2016-03-21-swift-2.2-released.md
_posts/2016-05-06-swift-3.0-release-process.md
_posts/2016-09-13-swift-3.0-released.md
_posts/2016-1-05-swift-2.2-release-process.md
_posts/2016-12-9-swift-3.1-release-process.md
_posts/2017-01-26-bridging-pch.md
_posts/2017-08-22-swift-local-refactoring.md
_posts/2017-10-17-swift-4.1-release-process.md
_posts/2017-2-16-swift-4.0-release-process.md
_posts/2018-01-19-forums.md

- This commit is part of the work to clean up all our broken links in #369. This can be shipped on its own, so I'm separating it out to keep the main PR as small as possible.
- This commit replaces links to `https://lists.swift.org/mailman/listinfo` with `https://lists.swift.org/pipermail/`
- In cases where we guide users to submit feedback, I've also added a `> Note` that explains that mailing lists are now closed and archived, and they should use forums instead.
- The posts with links to mailing lists are pretty old, but that fixes about 20-25% of all our broken links.

Fixed swift mailing lists links

---

_posts/2023-09-18-swift-5.9-released.md

Added the missing `if` keyword in front of let
Code with valid syntax

Fix code typo in the "Swift 5.9 Released" blogpost

---

_layouts/post.html

This PR reverses the preference order of the link used in blog post bylines.
This change will link to the author’s GitHub profile if present, then fall back to link to the Twitter/X profile if present, finally displaying no link if neither is present.
Twitter/X now requires being logged-in to view profile information. GitHub displays profile information without being logged-in. This change provides a better experience by not requiring a user to be logged into any service to view the profile information linked from a blog post byline.
The change is minor, changing the order in which presence of the account info is checked. I’ve tested this on a local copy of the site.

Prefer linking to GitHub profiles in blog post bylines

---

documentation/index.md

Someone suggested that such an invitation in this part of the site might make it more obvious that we're open to contributions.
Added a link and encouragement to contribute below the links to the Swift book on documentation/index.md.
Readers are more aware that the book is open to contributions.

Add an invitation to contribute to TSPL below its docs links.

---

assets/javascripts/swift-evolution.js

The Swift 5.10 release process was [announced](https://forums.swift.org/t/swift-5-10-release-process/66911).
Adding version 5.10 to the evolution dashboard script so proposals implemented in 5.10 will filter properly.

Add version 5.10 to evolution dashboard script

---

_posts/2023-09-28-whats-new-swift-debugging-5.9.md

Reported to me by a member of the community. Just a incorrect quote typo.

Fixed typo in a code sample in the 5.9 debugging post

---

install/windows/_winget.md

It seems, Installation Guide for Windows has incorrect version of Python specified.
See https://forums.swift.org/t/unable-to-debug-on-windows/67609
I've changed version of Python required from `3.10` to `3.9`
The issue with debugger is solved.

[Windows] Fixes version of the Python needed for LLDB to working properly

---

getting-started/vapor-web-server/index.md

I wasn't sure if I needed to run `swift build` then `swift run` or if `swift run` would suffice.
See: https://www.swift.org/getting-started/vapor-web-server/
Added the precise command to run and the expected output.
Ambiguity is gone. The unknown is known. Beginners can rush right through the tutorial without a second thought.

[vapor] Add `swift run` command for beginners

---

server/guides/deploying/ubuntu.md

Hi ! I found an error for the docker command from the Ubuntu deployment guide : 
**/workspace: error: package at '/workspace' is using Swift tools version 5.7.0 but the installed version is 5.2.0**
I just changed le bionic version from 2 to 7. The final command looks like this : 
```
docker run --rm \
-v "$PWD:/workspace" \
-w /workspace \
swift:5.7-bionic  \
/bin/bash -cl ' \
swift build && \
rm -rf .build/install && mkdir -p .build/install && \
cp -P .build/debug/NIOHTTP1Server .build/install/ && \
cp -P /usr/lib/swift/linux/lib*so* .build/install/'
```
This version works !

Documentation correction

---

assets/javascripts/swift-evolution.js

Until the Swift evolution parsing tool is updated, upcoming feature flags are included in the JavaScript that generates the Swift evolution dashboard.
This adds the upcoming feature flag for SE-409.

Add upcoming feature flag for SE-409

---

standard-library/_stdlib-design.md

Corrected link to SDK Overlays (`Darwin` to `Platform`)
Simply found and fixed a 404.
The `main` branch of *swift* does not contain the path `stdlib/public/Darwin`, but it does contain `stdlib/public/Platform`, which in-turn contains `Darwin.swift.gyb`.
No broken link! 🎉

corrected link to SDK overlays

---

install/windows/_scoop.md
install/windows/_winget.md

Revise the WinGet and Scoop installation guide to make them clearer and more robust.
Due to different CI environments being used, different Swift on Windows releases depend on different minor releases of Python. I’ve managed to update all WinGet manifests based on the [analysis](https://github.com/stevapple/swift-windows-toolchain-analysis), and we should drop manual dependency installation step and let WinGet decide what dependencies to install instead.
In `install/_winget.md`:
- No longer suggest users to manually install Git and Python;
- No longer require installing Python module `six`;
- Clarify the Visual Studio install step;
- Add a note about Visual Studio edition choosing.
In `install/_scoop.md`:
- No longer require installing Python module `six`;
- Add a note about Visual Studio …

Revise WinGet and Scoop installation guide

---

assets/javascripts/swift-evolution.js
swift-evolution/_dashboard.html

The next version of Safari removes the non-standard `search` event. This causes the search field on the evolution dashboard to stop working. The issue can be reproduced in Safari Technology Preview and Firefox.
This fix makes two changes:
- Uses the standard 'input' event instead of 'search' event
- Removes the non-standard 'incremental' attribute
The input event triggers the event listener on each change of input.
The behavior with this fix is unchanged to the behavior in the current Safari version.
Tested on macOS 14.1 in Safari, Chrome, Firefox, and Safari Technology Preview.
Fixes #440

Stop using non-standard search event on evolution dashboard

---

_data/website-workgroup/members.yml

Add Christopher Thielen to the website workgroup membership.

Add Christopher Thielen to website workgroup.

---

documentation/cxx-interop/project-build-setup/index.md

`classImpl.h` is not under the `cxxLibrary` directory. As a matter of fact, it is in the same directory as `cxxLibrary.h`, where `classImpl.h` is being included.

Fix C++ interop example

---

documentation/cxx-interop/index.md

[cxx-interop] Fix a typo in the C++ reference types docs

---

_data/server-workgroup/projects.yml

Add DiscordBM and Swift OpenAPI Generator as incubating projecs
The SSWG has accepted these projects as **sandbox** in the incubation process.
- Added the DiscordBM project
- Added the Swift OpenAPI Generator project
These projects should now show up at swift.org

Add DiscordBM and OpenAPI Generator as incubating projects

---

sswg/index.md

motivation: make the membership process more transperant
changes: bring over the sswg membership section from https://github.com/swift-server/sswg/edit/main/README.md to swift.org so it is more discoverable

add section about server workgroup membership

---

assets/stylesheets/pages/_landing.scss
index.md

This PR makes three minor changes to the preamble text on the swift.org landing page:
1. Begins the second sentence on a new line with a little padding above it. This makes the preamble feel less like a wall of text giving each sentence more breathing room.
2. Uses a smaller font size on mobile devices. This mirrors how other H1 headings are styled on the site.
3. Uses a typographer’s quote in the preamble.
The following screen captures show the before and after for both desktop and mobile:
---
---
---

Tweak landing page preamble

---

assets/javascripts/swift-evolution.js

This PR addresses Issue #467 
Without this fix, an invalid version or status in the fragment query of an evolution dashboard URL would display the filter interface. For an invalid version, it also gets the interface in a state where selecting the Implemented status hides the version filters.
Prior to this change, the script was checking the raw parameters in the query string rather than the array of validated values.
Finally this PR updates the comment that describes the fragment query syntax.

Fix issue 467

---

_data/documentation.yaml
documentation/index.md
documentation/server/index.md

changes:
* Articles -> Guides
* add link to new article (from rebase)
* Some article titles cleanup
* server guides landing page cleanup
* move compiler architecture under overview

[top naviagation] more docs cleanup

---

_data/packages/packages.yml

This update contains the January data file with new packages for the [Packages page](https://www.swift.org/packages/).
Packages in the Community Showcase were nominated in [this thread on the Swift forums](https://forums.swift.org/t/nominations-for-the-packages-community-showcase-on-swift-org/68168) and voted on by the [SWWG](https://www.swift.org/website-workgroup/).

Package page updates for January 2024

---

_layouts/post.html

Updates the post layout to fallback to the author's github profile image if their gravatar is not set.
Fixes #476

Fallback to github image if gravatar is nil

---

_config.yml

motivation: redirects seem to be broken atm, for example the https://www.swift.org/swift-compiler/ page has `redirect_from: compiler-stdlib` but that does not seem to work - https://www.swift.org/compiler-stdlib/ is not functional
changes: add the correct setup per https://github.com/jekyll/jekyll-redirect-from#how-it-works

fix redirects

---

assets/javascripts/swift-evolution.js

Add upcoming feature flag for [SE-0383](https://github.com/apple/swift-evolution/blob/main/proposals/0383-deprecate-uiapplicationmain-and-nsapplicationmain.md)
Swift 5.10 has `DeprecateApplicationMain` in [Features.def](https://github.com/apple/swift/blob/release/5.10/include/swift/Basic/Features.def)
Update swift-evolution.js
<https://www.swift.org/swift-evolution/#?upcoming=true>

Add upcoming feature flag for SE-0383

---

install/macos/_macos.md
install/macos/index.md

The Xcode version is read from the last entry of swift_releases.yml. Multiple Xcode versions can ship with the same Swift version, so the Xcode version displayed can be out of date.
The exact Xcode version is not very important to display on the page. So, instead of creating and maintaining an Xcode version data file, the text changes to say 'current version'.
Since the user will clicking through to the Mac App Store, they will see the correct version number on the app page in the store.
This fixes #493.

Use 'current version' instead of specific Xcode version

---

_includes/authors.html
_layouts/article.html
_layouts/page.html
_layouts/post.html
assets/stylesheets/_screen.scss
documentation/articles/value-and-reference-types.md
documentation/articles/wrapping-c-cpp-library-in-swift.md

This is follow-on work from content improvements.
At that time one documentation article was added. The author bylines for articles are at the bottom of the page, as opposed to blog posts where they are at the top. The layout of the bylines are the same for both.
For expediency, the byline CSS was copied and the byline HTML was added directly to single article. Now there are two articles with more likely to come, so this PR adds a layout for article and factors out the author bylines into a single HTML include and CSS.
A few other incidental clean up items are also included as detailed in the list below.
I tested this PR comparing to the live site and there were no visual changes in the author bylines. 
- Add article.html layout for documentation articles
- Move existing authors byline …

Add layout for articles and standardize author bylines

---

_data/documentation.yaml

Fixes a broken link reported by @mrcnski [here](https://github.com/apple/swift-org-website/pull/369#issuecomment-1913265108).
Once #369 is merged these should be caught in CI, but for now, we have to fix them manually.

Add missing .html suffix to documentation article link

---

assets/stylesheets/_screen.scss
blog/index.html

Slightly reduces header sizes to improve readability and removes excess whitespace.
before:
after:

Reduce H1 and H2 sizes

---

_data/authors.yml
_includes/authors.html

This PR removes unused Twitter handles from the `authors.yml` file and unused Twitter link markup from the `authors.html` file.
This follows up on the website workgroup's decision to use GitHub profiles as the external link for authors.
The reasons for this choice are:
- Github profiles can be viewed without being signed in / having an account. So they are accessible to all readers. (Twitter/X requires being signed in, which spurred the original preference for GitHub profiles.)
- GitHub profiles are flexible and allow a user to provide multiple social media accounts as well as a website and email address.
- GitHub is the service used for hosting Swift projects. The Swift.org blog submission process includes submitting a PR, so , to date, all contributors to Swift.org have a GitHub …

Remove unused Twitter handles and markup

---

README.md

The README file list Ruby 3.1 as min version, instead it should say Ruby 3.2
Update README file with Ruby upgraded version
README has Ruby 3.2

Update README with min Ruby 3.1 to Ruby 3.2

---

_posts/2024-01-31-swift-openapi-generator-1.0.md

Fix a typo in the OpenAPI post.
Fixed a typo.
The typo is no more.

Fix a typo in the OpenAPI post

---

gsoc2024/index.md

This is necessary for our GSoC 2024 application so we need to get this merged right now, even if still empty.
It is the same shape of page and content as we did for all previous years -- could I request a quick merge here and we can then follow up with adding more content? @alexandersandberg @0xTim et al?

Project ideas page for GSoC 2024

---

gsoc2024/index.md

Sorry, minor addition, follow up to https://github.com/apple/swift-org-website/pull/513 -- wanted to offer a direct link to make a pull request to the newly added website.

GSoC Add pull request link to 2024 page

---

assets/javascripts/swift-evolution.js
assets/stylesheets/pages/_swift-evolution.scss

The proposal.json file that provides the evolution dashboard its data always puts a space character at the beginning of every title.
This change trims the title and adjusts the margin of the preceding element so there is no visual change to the page.

Trim proposal titles and adjust spacing in evolution dashboard

---

gsoc2024/index.md

Also add the required difficulty section and change the times to concrete hours, as GSoC requested, rather than "medium" etc.

[gsoc] Add project idea: Tracing in HTTP client

---

gsoc2024/index.md

Fix some garbled test in my GSoC '24 entry on lexical scopes.

Correct garbled text

---

gsoc2024/index.md

Syntax was broken in server project

GSoC 2024: fix broken link syntax

---

gsoc2024/index.md

Add a GSoC proposal to write a generator that would convert the SAM template definition to a set of Swift data structures that can be used by the SPM deployer plugin

Add GSoC proposal for AWS Lambda Runtime + SAM

---

gsoc2024/index.md

The `|` makes markdown think the name is a table and render it weird:

GSoC 2024 fix formatting

---

documentation/cxx-interop/index.md

Swift 5.9 is here. Updating the page to remove the comments about it being in development.

Tighten opening language for Swift C++ interop

---

documentation/articles/wrapping-c-cpp-library-in-swift.md

Fixed the link to the Swift-CMake examples repository on Github in the article [Wrapping C/C++ Library in Swift](https://www.swift.org/documentation/articles/wrapping-c-cpp-library-in-swift.html) in the CMake section.
Improve swift documentation
Fixed the link to the Github repository
The correct link

Fix Github swift-cmake-examples link

---

_data/navigation.yml

The last couple of times I’ve used the Swift.org menu to look at the package pages I’ve found myself wishing there was a more obvious way to figure out that there’s information on the top-level page, too.
This PR adds “Overview” menu items at the top of the Packages and Community menus that take visitors to `/packages/` and `/community/` respectively. It does not remove the links from the top-level menu item, only adds one more link.

Added Overview links to the Packages and Community menus

---

_data/packages/packages.yml

This month's links to the sources for community showcase nominations lost their `target=blank` attributes.
Add back the `target=blank` attributes.
Blank targets everywhere! 🫨

Add back missing target=blank on Package page Community Showcase source links

---

sswg/index.md
website-workgroup/index.md

Fixes #558 
- Removed the extra space in the SSWG and SWWG lists
We can probably create a reusable list component for this at some point, but this is good enough for now.
Clean!

Remove extra space in person lists

---

assets/javascripts/swift-evolution.js

Add version 6.0 to the evolution list's implemented filter.
As we have some proposals marked as implemented in Swift 6.0, we should add this version to the evolutions filter as well.
- Adds `6.0` to the filter
You can filter the evolutions list by "implemented in Swift 6.0" (currently 8 results).

Add Swift 6.0 to evolutions list filter

---

_data/featured_snippets.yml
assets/stylesheets/_mobile.scss
assets/stylesheets/_screen.scss
assets/stylesheets/pages/_landing.scss
index.md

Now that the homepage has a wider template we can move the Swift callout (and have it bigger) and the code box in the same row to reduce scrolling and have more content visible (without scrolling)
Changed the CSS in:
```
assets/stylesheets/_screen.scss
assets/stylesheets/_mobile.scss
assets/stylesheets/pages/_landing.scss
```
Changed the structure of the `callout` section in homepage in:
```
index.md
```

Add top section layout change

---

assets/stylesheets/pages/_packages.scss
packages/_get-involved.html
packages/_package-list.html
packages/index.md

As discussed in the SWWG, we should make the [nominations thread](https://forums.swift.org/t/68168) for Community Showcase packages more prominent to encourage more community members to get involved if they are not frequent visitors to the Swift forums.
Adds a CTA to both the Packages overview page, and the Community Showcase package list.

Add a more prominent CTA to the nomination thread for Community Showcase packages

---

packages/_package-list.html

I just went to link directly to the Archive heading in the new section and because it's an HTML file not a Markdown file, it doesn't get the automatic `id` attribute. This PR adds that for the heading element.
Linked to from https://github.com/apple/swift-org-website/issues/566

Make the Community Showcase archives directly linkable

---

_posts/2020-08-27-swift-cluster-membership.md
_posts/2022-12-05-swift-summer-of-code-2022-summary.md
_posts/2023-05-18-evolving-swift-project-workgroups.md
documentation/server/guides/allocations.md
documentation/server/guides/performance.md

Improve image alt texts across the website, to not simply be empty or "image".
Alt texts are important for accessibility and to provide an alternative text in case the image fails to load.
- Wrote alt texts for some images that were missing alt text or simply had an alt text of "image"
- Remove a few instances of `{{ site.url }}` being used in links, as it's not necessary
- Better accessibility

Improve image alt texts

---

gsoc2024/index.md

I've reviewed the Google Summer of Code 2024 project ideas and observed they are predominantly categorized as "Intermediate" in difficulty. To broaden the appeal and accessibility for participants with diverse skill levels, I propose adding projects classified as "Easy," starting with "Creating Real-World Swift Macro Examples with Documentation and DocC Tutorials."
This project is designed to fill a gap in practical Swift Macros applications, providing beginners with a straightforward entry point into Swift development. It will focus on developing practical Swift Macro examples, complete with diagnostics, unit tests, and comprehensive DocC tutorials.
Incorporating "Easy" difficulty projects could enhance the program's inclusivity, allowing participants at the start of their development …

Add project idea to Create Real-World Swift Macro Examples

---

_data/authors.yml
_posts/2024-03-03-pack-iteration.md
_posts/2024-03-07-pack-iteration.md

Add a blog post about pack iteration ([SE-0408](https://github.com/apple/swift-evolution/blob/main/proposals/0408-pack-iteration.md)) and how to use it, featuring a brief overview of parameter packs ([SE-0393](https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md)).
This is my first blog post, so I will appreciate any feedback! 
With the introduction of parameter packs in Swift 5.9, there was a demand for pack iteration support using a `for`-`in` loop syntax. [SE-0408](https://github.com/apple/swift-evolution/blob/main/proposals/0408-pack-iteration.md) enabled pack iteration for Swift 6.0, and it makes interacting with parameter packs way more straightforward for a Swift programmer. I wrote this blog post to introduce folks with parameter packs and show a …

Add Pack Iteration blog post

---

_posts/2024-03-07-pack-iteration.md

- In the initial version of the post, fix that the types of the tuples being compared did not match by making them the same type. 
- Also, fix the call site explanation by explicitly noting that one parameter pack `each Element` represents the types of the two tuples.

Fix typo in Pack Iteration post

---

_posts/2024-03-07-pack-iteration.md

Fix another typo: use `Equatable` in the `==` signatures in the first section. I had a `<` operator there before so I forgot to update the protocol when I changed the operator to `==`

Pack Iteration post: Change `Comparable` to `Equatable` in the `==` operator signature

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the new data file with new packages for the [Packages page](https://www.swift.org/packages/). It also moves last month's packages into the archive.
Packages in the Community Showcase were nominated in [this thread on the Swift forums](https://forums.swift.org/t/nominations-for-the-packages-community-showcase-on-swift-org/68168) and voted on by the [SWWG](https://www.swift.org/website-workgroup/).
All other packages are updated based on search ranking on the [Swift Package Index](https://swiftpackageindex.com/).

Package page updates for March

---

assets/stylesheets/_screen.scss

Safari won't display SF Font families if you installed the official distribution and try to use it with `font-family: "SF Mono"`. So in my Safari the code font fallbacks to Menlo. 
This PR fixes it and it should also work even if the Safari users didn't install SF Mono.
Added `ui-monospace` to styles.
```css 
pre,
code {
font-family: "SF Mono", ui-monospace, Menlo, Consolas, Monaco, "Courier New", monospace,
serif;
}
```
The left is original, the right one is updated.

Add ui-monospace for code display in Safari

---

_posts/2024-03-12-byte-sized-swift-tiny-games-playdate.md

Adds a missing "pd_api" to an "ls" command used in the playdate blog post.

Add missing directory to blog post

---

CODEOWNERS
_data/website-workgroup/emeriti.yml
_data/website-workgroup/members.yml

Make website workgroup membership updates to be merged along with forum post announcement.
- Add Federico Bucchi as a member
- Move Tim Triemstra and Tom Doron to the emeritus list
- Designate Paris Pittman as the Core Team rep

March 2024 SWWG Membership updates

---

_data/documentation.yaml
code-of-conduct/index.md
community/_forums.md
community/index.md
contributing/_contributing-code.md
contributor-experience-workgroup/index.md
diversity/index.md
documentation-workgroup/index.md
documentation/server/index.md
language-steering-group/index.md
sswg/index.md
support/security.md
website/index.md

Punctuation in lists is missing or is inconsistent.
Fixed inconsistencies in the following doc/files:
- _data/documentation.yaml
- code-of-conduct/index.md
- community/_forums.md
- community/index.md
- contributing/_contributing-code.md
- contributor-experience-workgroup/index.md
- diversity/index.md
- documentation-workgroup/index.md
- documentation/server/index.md
- language-steering-group/index.md
- sswg/index.md
- support/security.md
- website/index.md
Most of punctation inconsistencies are now fixed (I am saying most because I might have missed something)

Fix punctuation

---

_includes/navigation.html
assets/stylesheets/_screen.scss
assets/stylesheets/core/colors/_dark.scss
assets/stylesheets/core/colors/_light.scss

As per,
- #502 
made changes to highlight current page in the navigation bar.
- Updated `navigation.html`
- Updated active color to a variable `--color-active-nav-item`
The current page will be highlighted in the navigation bar.

Highlight current page in the navigation bar

---

assets/javascripts/swift-evolution.js

Small refactoring PR to consolidate URL constants at the top of the script and make them `const` instead of `var`.
Also add a constant for the URL for the evolution metadata JSON file. This also makes it easier for testing the new JSON file URL during development.

Consolidate constant urls at top of script

---

assets/javascripts/swift-evolution.js

This PR allows the SE Dashboard script to work with the current JSON schema and the new JSON schema.
This facilitates development and testing during the transition to the updated schema as detailed here; https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779
Tested with both the existing JSON file at:
`https://download.swift.org/swift-evolution/proposals.json`
And a test version of the proposed schema at:
`https://download.swift.org/swift-evolution/v1/evolution.json`
From the user's standpoint, there is no observable change in the page.

Add ability for dashboard script to work with current and proposed schemas

---

documentation/server/guides/memory-leaks-and-usage.md

Edited for further clarification and usefulness.
Expanded definitions and meanings, completed sentence structures, formatted for ease of readability, included extra links/instructions, etc.
Aims to improve helpfulness. Notably, for those who are less familiar or new to Swift on Server.

Overhauled debugging memory leaks

---

_posts/2024-03-20-benchmarks.md

Minor correction to the Benchmark blog post title to avoid making it sound like Swift project core package.
Changes the title of the most recent blog post.

Tweak the title to remove the official-sounding package name

---

documentation/server/guides/memory-leaks-and-usage.md

Documentation isn't formatting correctly, potentially confusing user instructions and examples.
Corrected syntax and adjusted spacing. 
Correct formatting and flow of information.

Reformatted debug mem leak doc

---

assets/javascripts/swift-evolution.js

An update to allow the SE Dashboard script to continue to work with the current JSON schema and the new JSON schema.
The feedback on the proposed schema reduced the required change to the status field. Now, only a dot needs to be prepended to the new status state value.
This facilitates development and testing during the transition to the updated schema as detailed here; https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779
Tested with both the existing JSON file at:
https://download.swift.org/swift-evolution/proposals.json
And a test version of the proposed schema at:
https://download.swift.org/swift-evolution/v1/evolution.json
From the user's standpoint, there is no observable change in the page.

Update evolution script for proposal changes

---

documentation/cxx-interop/index.md

Swift now supports templated `operator==` (https://github.com/apple/swift/issues/66767). This change updates the C++ interop documentation to reflect that.

[cxx-interop] Remove outdated doc item

---

.gitignore
.prettierrc
assets/stylesheets/_colors-basic.scss
assets/stylesheets/_mobile.scss
assets/stylesheets/_print.scss
assets/stylesheets/_screen.scss
assets/stylesheets/_syntax.scss
assets/stylesheets/core/_colors.scss
assets/stylesheets/core/_maps.scss
assets/stylesheets/core/_reset.scss
assets/stylesheets/core/_vars.scss
assets/stylesheets/core/colors/_dark.scss
assets/stylesheets/core/colors/_light.scss
assets/stylesheets/docc/footer.css
assets/stylesheets/docc/header.css
assets/stylesheets/pages/_getting-started.scss
assets/stylesheets/pages/_landing.scss
assets/stylesheets/pages/_swift-evolution.scss

Stylesheet source files used a mixture of 2-space and 4-space based indentation.
Make all stylesheet files use 2-space indentation.

Use consistent stylesheet indentation

---

install/windows/_winget.md

Related to: https://github.com/apple/swift-org-website/issues/516
I think that just adding the link to /install/windows would leave the user again on an unexpected place.  What about having a first step that reminds again on taking care of dependencies?
Add link to dependencies on step 1 for **Installation via Windows Package Manager**
User is now aware of Dependencies without having to scroll up

<516> Add link to dependencies

---

platform-steering-group/index.md

Introduce the charter for the newly formed Platform Steering Group to the website.

Add the Platform Steering Group Charter

---

_data/navigation.yml

The charter and info about the new Platform Steering Group was added to the site with PR #624.
However, the content landed without adding a link to the new group in the Workgroups section in the Community menu.
This PR adds an entry in the navigation.yml file for the new steering group.

Add Platform Steering Group to community navigation

---

_includes/navigation.html
assets/stylesheets/_screen.scss

https://github.com/apple/swift-org-website/issues/502
> The menu items shouldn't jump after changing pages
Added style in: `assets/stylesheets/_screen.scss`
The menu items are not shifting after the page change

<502> Remove jump when switching page

---

_data/packages/packages.yml

I'm going to do this month's package page updates in two pull requests for easier reviewing.
This first pull request contains no human-curated changes, only updates to ranking, compatibility, and other automated metadata since last month. This data is provided by the Swift Package Index.
#631 then includes this month's Community Showcase packages.

Packages page search ranking and compatibility updates

---

contributor-experience-workgroup/index.md

Currently, the swift repository docs [are asking](https://github.com/apple/swift/blob/ee24bdf06f59d05fea996c230eb4024aa04dd4f5/docs/HowToGuides/FirstPullRequest.md#:~:text=message%20the%20Contributor%20Experience%20Workgroup) contributors to message the workgroup on the forums for help, which is a drag when you can simply reach out to a member in that same issue or pull request. These links will enable us to direct people to the charter's member list instead.
Also, reformat the member list into a table, which is easier to visually parse with links to multiple accounts.
—
___
Paired with https://github.com/apple/swift/pull/72729.

Contributor Experience Workgroup: Add links to members' GitHub accounts

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

Rebase on top of #630 before merging.
This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for April.

April Community Showcase packages

---

assets/stylesheets/_screen.scss
assets/stylesheets/core/_colors.scss
assets/stylesheets/core/colors/_dark.scss
assets/stylesheets/core/colors/_light.scss

Currently, we use an orange color that's slightly off from the "Swift orange" color for the active nav item color. Furthermore, we _do_ actually use the Swift orange color, but only in the mobile menu. We should align these.
I propose to just use the Swift orange color in both light and dark mode as it works well, and is more on-brand than at the moment.
- Add a new "swift-orange" color
- Use this color consistently for active nav items
|Before|After|
|---|---|
|![CleanShot 2024-04-05 at 09 58 15](https://github.com/apple/swift-org-website/assets/35671299/7a76992c-7290-456e-b205-b80df830a4b1)|![CleanShot 2024-04-05 at 09 59 47](https://github.com/apple/swift-org-website/assets/35671299/e53f7a65-1897-4ec2-ae8c-6536e2c63563)|
|Before|After|
|---|---|
|![CleanShot 2024-04-05 at 09 58 …

Use Swift orange color for all active nav items

---

documentation/api-design-guidelines/index.md

API design guidelines document has a couple of typos in word "subviews".
Fixing the typo from `subViews` to `subviews`.
The word "subviews" is spelled correctly now.

Correct "subviews" spelling in API design guidelines

---

_layouts/page.html

We're using the `<footer>` element on `article` layout pages for the author bylines. This is styled with some margin and a divider between the content and the authors.
We should use this on `page` layout pages too, to keep the styling consistent.
Using a `<footer>` element here will also improve the semantics of the HTML for the `page` layout.
- Replaced the `<hr>` in the `page` layout with a `<footer>`
|Before|After|
|---|---|
|![CleanShot 2024-04-10 at 20 58 12](https://github.com/apple/swift-org-website/assets/35671299/12e3feae-2376-4ea8-baf5-540c29917a63)|![CleanShot 2024-04-10 at 20 57 51](https://github.com/apple/swift-org-website/assets/35671299/fcc40bd8-3820-4091-b62c-d890c5ff99cc)|
Which now looks the same as the blog posts' footer:

Improve page layout with <footer> element

---

_data/packages/packages.yml
_data/packages/showcase-history.yml
_plugins/packages.rb
assets/javascripts/application.js
assets/stylesheets/_screen.scss
packages/_history.html
packages/_package-list.html

https://github.com/apple/swift-org-website/issues/566
- Added years in `showcase-history.yml` and include months in each year.
- Loop years instead of months in the view (`_package-list.html`), then loop the months inside each year)
- Add `JS` to make year tabs interactive and show the correct list of months (after you click on an year).
- Add style to handle the new archive view in `_screen.scss`

<566> Add years in community showcase archive

---

assets/stylesheets/pages/_swift-evolution.scss

Fixes #636 
The CSS is a bit unstructured atm so this may not be the absolute best long-term solution, but at least it fixes it for now.

Fix evolution dashboard authors row

---

assets/javascripts/swift-evolution.js

The SE Dashboard script has been using a temporary mapping of proposal ID to upcoming feature flag until the metadata JSON file contained that information.
The metadata JSON file is about to begin providing upcoming feature flag values. It provides them as an object with a `flag` field (and other optional fields) instead of as a string.
This PR adjusts the script to access the flag field. It also updates the temporary mapping to match the structure of the soon to be available metadata file.
This PR has been tested with the existing `proposal.json` metadata file and a version of the file with the metadata file changes.

Update temp upcoming feature flag values to match metadata file

---

assets/javascripts/swift-evolution.js

This PR migrates the SE Dashboard script to the new metadata schema file.
Details of the schema changes are available in the proposal:
https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779
Note this PR consists of multiple commits. It may be easier to review by looking at each commit on its own.
This PR:
- Uses the new metadata file located at `https://download.swift.org/swift-evolution/v1/evolution.json'
- Removes legacy file conditional code and the hard-coded language version array
- Uses the new `implementationVersions` field for language versions
- Updates top-level variables to use `let`
- Removes hard-coded upcoming feature flags and uses the ones now provided in the metadata
- Migrates to the new `reviewManagers` field to handle cases with multiple review …

Migrate SE Dashboard script to new metadata schema file

---

assets/javascripts/swift-evolution.js

This PR migrates the SE Dashboard script to use the new state values for proposal status. 
Essentially values previously had a leading dot (i.e. ".accepted") and now do not (i.e. "accepted")
Details of the schema change is available in the proposal:
https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779
This PR does two main things:
1. Moves to using string constants for proposal state values instead of bare strings throughout the script
- The string constants are defined in a frozen `State` object
2. Migrates to the new state values
- Updates the string contents
- Removes the reviver function that added a leading dot. This allowed the script to work with both the old and new schema, but is no longer required. 
I have tested the change, including filters, and behavior …

Migrate dashboard script to new status values

---

documentation/server/guides/memory-leaks-and-usage.md

Fix the sequential number list starting over after a block of code.
Manually override Markdown's handling of numbered lists. 
Maintain the continuity of sequential numbering.

Fix number format starting over after a block of code

---

_layouts/post.html
blog-post-contributions/index.md

Fixes an empty "Written by" headline in the footer on https://www.swift.org/blog-post-contributions/
- Only show the 'Written by' headline in the footer if the post has one or more authors
- Change the layout for /blog-post-contributions/ to `page`, as it better suits the content
- No empty footer on /blog-post-contributions/
- Other posts with authors have not changed
- In case we use the `post` layout for a page that doesn't have an author in the future, this empty headline will no longer be shown

Fix empty 'Written by' headline on blog post contributions page

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

Rebase on top of #653 before merging.
This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for May.

May Community Showcase packages

---

install/index.md

Help developers to get started with documentation.
Added user-friendly language and simple steps for clarity.
Provide new users and developers with an instructional vs functional approach.

Edited installing swift index 

---

community/index.md

- #638 
Added entries for `Contributor Experience Workgroup` and `Platforms Steering Group`, with description copied from each individual page while maintaining similar standards in wording as opposed to other group/workgroups.
Contributor Experience Workgroup and Platforms Steering Group will be added

feat: add Contributor Experience Workgroup and Platforms Steering Group

---

_includes/getting-started/_installing.md

Help developers get started using Swift.
Lightly edited "getting started > installing swift" 
Help new users get started using swift from an instructional vs. functional approach.

Robins install swift changes

---

install/linux/index.md

Create an overview section that briefly explains option benefits and outlines page content.
Added overview to top. 
Help users understand the option's purpose and the benefits of using Linux.

Added overview for Linux Installation Options

---

download/index.md

[Download] Add Ubuntu 23.10 and Ubuntu 24.04 to the nightly Swift 5.10

---

documentation/cxx-interop/index.md

The macro was misspelled in the documentation. Here is its definition: https://github.com/apple/swift/blob/d494632e98dec4246764c5082ab495faefea7678/lib/ClangImporter/SwiftBridging/swift/bridging#L120-L121
rdar://129031477

[cxx-interop] Fix typo: `SWIFT_CONFORMS_TO` -> `SWIFT_CONFORMS_TO_PROTOCOL`

---

documentation/server/guides/allocations.md

Edited documentation to improve helpfulness for new and experienced Swift on Server (SOS) users.
Added definitions and explanations where needed, edited existing content for clarity, and formatted for scannability. 
Increase user adoption and bolster the SOS community.

Overhauled allocations documentation for helpfulness

---

documentation/server/guides/performance.md

I edited Debug Performance Issues and Analysis documentation to increase helpfulness.
I overhauled page content by adding definitions and clarity to existing content, editing for grammar and complete sentences, reducing wordiness, providing additional instructions for less-skilled users, and formatting for scannability.
Improve usefulness and increase user adoption.

Ported overhauled performance.md doc file changes

---

assets/stylesheets/_syntax.scss

This means that we can have nicely formatted sequences of shell commands with output without it being unclear, while also making it easy to copy just the command without getting the prompt as well.
Here's what it looks like in action:

Mark prompts as non-selectable.

---

documentation/articles/zero-to-swift-emacs.md

Add an article showing how to get started with Swift using Emacs.
rdar://127610658

[Articles] Add Emacs article.

---

_includes/getting-started/_installing.md

Updated language.
Changed wording from **Swift** to **Apache 2.0** license.
Provide accuracy.

Changed wording from Swift to Apache 2.0 license

---

_data/documentation.yaml
documentation/articles/static-linux-getting-started.md

First pass at a Getting Started document for the Static Linux SDK.
rdar://129217209

Add a Getting Started document for the Static Linux SDK.

---

_data/documentation.yaml
getting-started/_use-cases.md
getting-started/embedded-swift/index.md

Adding a new "Getting Started" guide, alongside the other guides/tutorials. This one describes how to get started with Embedded Swift by building a simple firmware for a Raspberry Pi Pico, with the option of running the result in a simulator instead of a physical device.

Add a new 'Getting Started' guide for Embedded Swift and writing an application for a microcontroller

---

install/index.md
install/linux/amazonlinux/2/index.md
install/linux/amazonlinux/index.md
install/linux/centos/7/index.md
install/linux/centos/index.md
install/linux/debian/12/index.md
install/linux/debian/index.md
install/linux/fedora/39/index.md
install/linux/fedora/index.md
install/linux/index.md
install/linux/ubi/9/index.md
install/linux/ubi/index.md
install/linux/ubuntu/20_04/index.md
install/linux/ubuntu/22_04/index.md
install/linux/ubuntu/23_10/index.md
install/linux/ubuntu/24_04/index.md
install/linux/ubuntu/index.md
install/macos/index.md
install/windows/index.md
install/windows/traditional/index.md

This page like the Homepage, Getting Started, Packages and Tools can be made wider
Applied `page-wide` class to all Install pages

Apply wider template to Install page

---

assets/javascripts/swift-evolution.js

Update the GitHub URL in the evolution dashboard script to use the new `swiftlang` organization.

Update GitHub URL in evolution dashboard script for swiftlang org

---

documentation/articles/zero-to-swift-nvim.md

There were some missing closing quotes on some strings in the autocomplete configuration code snippet in the article for setting up Neovim for Swift development.

Fix strings in autocomplete snippet

---

_includes/install/_linux_platforms_tabs.md

Suggestion from #676 by @daveverwer.
- Add Linux version to the Linux platform tab if only one version is available to select from
Note: The best implementation of this would be to store the platforms/versions in a data file and dynamically (at build-time) decide whether we should directly link to the version or not based on the data.
I did start working on this but decided to go for this simpler, manual implementation for now as I think in general the install page data can be reworked to not only store the platforms/versions in a data file but also _generate the pages_ based on this data.
@shahmishal @federicobucchi let me know what you think about this—whether this quick implementation is still worth it or if we should consider the data file solution right away.
On /install, clicking a …

Preselect Linux version on /install if only one version available

---

_data/server-workgroup/emeriti.yml
_data/server-workgroup/members.yml

Fixes #716 
- Moved Tom Doron to the emeritus list + added Dianna Ma, Ben Cohen, and Tibor Bödecs
- Fixed Sven A. Schmidt's affiliation not rendering due to an incorrect property name

Update SSWG members

---

CODEOWNERS

Update CODEOWNERS to assign Tim Sneath to blog review, replacing me.
Tim Sneath is taking over blog review duties.
Update CODEOWNERS to reflect role change.
Tim Sneath will have the ability to review blog PRs.

Assign Tim Sneath to the blog

---

documentation/articles/getting-started-with-vscode-swift.md

Mostly renames for consistency within the guide.
- Consistently use SourceKit-LSP as the spelling
- Consistently refer to _VS Code_ after introducing the abbreviation for _Visual Studio Code_ at the start of the article.

Minor improvements to the VS Code extension set-up guide

---

documentation/articles/static-linux-getting-started.md

Confusingly, SwiftPM has two options, `--sdk` and `--swift-sdk`, and they do different things.  You need `--swift-sdk` for the downloadable SDK feature.

It should be `--swift-sdk`, not `--sdk`.

---

assets/stylesheets/core/colors/_dark.scss
assets/stylesheets/core/colors/_light.scss
assets/stylesheets/pages/_landing.scss
index.md

Add a banner to direct users to the Swift 6 language mode migration guide.
- Add banner to landing page + add necessary CSS
- Note: I'm using an absolute URL here as the migration guide is not hosted in this repository and will otherwise show up as a "not found" page when running locally
Live preview: https://alexandersandberg-swift-org-banner.netlify.app

Add Swift 6 language mode migration banner to landing page

---

mentorship/index.md

Some of the information on the Mentorship program page is outdated, this is an attempt to rectify that.
- Replace Diversity in Swift with Contributor Experience workgroup which took over this responsibility;
- Update FAQ about how to become a mentor to point to the ongoing survey.

Mentorship Program page improvements

---

assets/stylesheets/_screen.scss

When the content is the page is short, the footer aligns in too high.
Added style changes in _screen.scss
Before
After

Fix footer position

---

_posts/2017-01-18-swift-evolution-status-page.md
_posts/2022-07-01-swift-language-updates-from-wwdc22.md
_posts/2022-09-12-swift-5.7-released.md
_posts/2023-03-30-swift-5.8-released.md
_posts/2023-09-18-swift-5.9-released.md

GitHub Pages shows 404 (file not found) instead of automatically redirecting to the new organization.
Several blog posts contain links to
https://apple.github.io/swift-evolution/
which doesn't automatically redirect to
https://swiftlang.github.io/swift-evolution/
Link directly to the SE dashboard at
https://www.swift.org/swift-evolution/
Links in blog posts are repaired.

Repair links to SE dashboard

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains new [Community Showcase packages](https://www.swift.org/packages/showcase.html).
I don’t know how I managed to forget this but the June packages never made it onto the site, so this PR includes both June *and* July packages.

Updated Community Showcase packages

---

mentorship/index.md

* Change heading from "Interest Surveys" to "Participation". The latter
is a simpler and more catchy word.
* Don't repeat info that is already in the timeline.
* The program duration is measured in weeks. Express time commitment in
hours/week too.
* Clarify that the exit survey is not compulsory.
* Add link to mentee interest survey

[Markdown] A few improvements to mentorship page 

---

documentation/server/index.md
sswg/incubated-packages.md
sswg/incubation-process.md
sswg/index.md

Fixes #759 
For some reason that I'm not sure of, some SSWG links, but not all, require the `.html` suffix. Is this some server setting? cc: @shahmishal
- Fixed 1 /sswg/incubated-packages.html link
- Fixed 3 /sswg/incubation-process.html links
Links work again.

Fix SSWG links

---

documentation/package-manager/_basic-usage.md
documentation/package-manager/_conceptual-overview.md

We recently had [an issue](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/discussions/3197) raised with SPI where someone thought the rule that `Package.swift` manifests must be located at the root of the package repository was something that SPI was enforcing rather than a SwftPM requirement.
I thought (and subsequently double-checked) that it was a SwiftPM requirement for library packages, but my first step in those checks was to search the web and this page was the first official source that came up. It struck me that this would be a good place to make this requirement clear.
Clarified the Creating a Library Package section of the SwiftPM page to make this clear.

Clarify that package manifests must be located at the root of the repository in the Conceptual Overview section of the SwiftPM page

---

_data/navigation.yml

As steering groups are not workgroups ([blog post that explains the difference](https://www.swift.org/blog/evolving-swift-project-workgroups/)), I don't think they should not be listed under "workgroups", but rather in their own "steering groups" section.
I think this makes the community drop-down easier to understand and quicker to scan as well.
- Moved steering groups into their own section and removed the "steering group" suffix
|Before|After|
|---|---|
|![CleanShot 2024-07-15 at 18 34 56](https://github.com/user-attachments/assets/1e411de2-9fd1-4aa7-be49-188e060478e7)|![CleanShot 2024-07-15 at 18 34 13](https://github.com/user-attachments/assets/602e9b4a-414e-4a6c-8cd9-5f8f27547b4b)|

Move steering groups to own section in community drop-down

---

contributing/_contributing-code.md

In an effort to centralize information about the release process, including guidance on formatting a release branch pull request, dedicate a section to this for repositories and forum announcements to refer to.
—
—

[Markdown] Contributing: Add section about release branch PRs

---

_includes/linux/table.html
_includes/linux/ubuntu2204.html

The website no longer has a section on the dependencies that should be downloaded on Ubuntu 22.04.
I assume this was mistakenly removed when adding Ubuntu 23.10 and 24.04.
<kbd> <img width="512" alt="Screenshot 2024-07-28 at 8 03 19 PM" src="https://github.com/user-attachments/assets/f76854c5-ca87-485f-be02-6596ba75133b"> </kbd>
https://www.swift.org/install/linux/tarball/
Re-add that section.
The Ubuntu 22.04 dependencies have been updated as well, according to the [Dockerfiles](https://github.com/swiftlang/swift-docker/blob/main/5.10/ubuntu/22.04/Dockerfile).
Users know what dependencies to install on Ubuntu 22.04.

Re-add Ubuntu 22.04 download section

---

_data/authors.yml
_posts/2024-07-30-announcing-swift-homomorphic-encryption.md

Introduce Swift Homomorphic Encryption (https://github.com/apple/swift-homomorphic-encryption) for wider visibility in the Swift ecosystem.
Add a blog post introducing Swift Homomorphic Encryption. The date and `published: false` are placeholders, for a possible future publication date (TBD).
We'll have a blog post for Swift Homomorphic Encryption.

Add blog post: Announcing Swift Homomorphic Encryption

---

documentation/articles/wrapping-c-cpp-library-in-swift.md

Added hypertext links in the article [Wrapping C/C++ Library in Swift](https://www.swift.org/documentation/articles/wrapping-c-cpp-library-in-swift.html).
Improve swift documentation and make it better
URLs in the article that were full-size are formatted as hypertext links
Beautiful Hypertext links 
1. **External Project**
2. **FetchContent & find_package** 
3. **Find SQLite3 & Module Map Language**

Add hypertext links in the article Wrapping C/C++ Library in Swift

---

_posts/2024-07-30-announcing-swift-homomorphic-encryption.md

Add missing hyperlink to Announcing Swift Homomorphic Encryption blog post.

Add missing hyperlink to Announcing Swift Homomorphic Encryption

---

_data/builds/development/static_sdk.yml
_data/builds/swift-6_0-branch/static_sdk.yml
_includes/install/_static_sdk_dev.md

To support the new feature in Swift Package Manager (static Linux SDK for Swift).

Add support for checksum to install page for static Linux SDK

---

_data/builds/swift_releases.yml
api/v1/install/dev/6.0/amazonlinux2.json
api/v1/install/dev/6.0/centos7.json
api/v1/install/dev/6.0/macos.json
api/v1/install/dev/6.0/static-sdk.json
api/v1/install/dev/6.0/ubi9.json
api/v1/install/dev/6.0/ubuntu2004.json
api/v1/install/dev/6.0/ubuntu2204.json
api/v1/install/dev/6.0/windows10.json
api/v1/install/dev/main/amazonlinux2.json
api/v1/install/dev/main/centos7.json
api/v1/install/dev/main/macos.json
api/v1/install/dev/main/static-sdk.json
api/v1/install/dev/main/ubi9.json
api/v1/install/dev/main/ubuntu2004.json
api/v1/install/dev/main/ubuntu2204.json
api/v1/install/dev/main/windows10.json
api/v1/install/releases.json

Swift.org install api to support installer tools (Swiftly)
To support Swiftly, I propose static JSON API endpoints from YAML files that will be created during the Jekyll build phase. These endpoints will allow users to access a list of releases at `swift.org/api/v1/install/releases.json`, containing information about tags, platforms, architectures, and docker tags. The dev endpoint, `swift.org/api/v1/install/dev/<branch>/<platform>.json`, will provide a list of development toolchain information. In the future, we should provide REST APIs which can be dynamic and supports query parameters. 
```
├── api
│   └── v1
│       └── install
│           ├── dev
│           │   ├── 6.0
│           │   │   ├── amazonlinux2.json
│           │   │   ├── centos7.json
│           │   │   ├── macos.json
│ …
```

Swift.org install api to support installer tools (Swiftly)

---

assets/stylesheets/_elements.scss
assets/stylesheets/application.scss
assets/stylesheets/core/colors/_dark.scss
assets/stylesheets/core/colors/_light.scss
assets/stylesheets/elements/_banner.scss
assets/stylesheets/pages/_landing.scss
index.md
packages/_get-involved.html

Unifies the banner and cta css styles used on multiple pages.
Moves the element to a common location so the it can be found in the
source easily and be reused across pages.

Reduce duplicated code for banners

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

Merge after #777
This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for August.

Updated Community Showcase packages for August

---

assets/stylesheets/core/_colors.scss
assets/stylesheets/core/colors/_dark.scss
assets/stylesheets/core/colors/_light.scss

Removes figure-gray-secondary-alt in favor of figure-gray-tertiary which already had the exact same color values.
Fixes fill-quaternary to have different colors in dark and light mode.

Fix duplicated grays

---

Gemfile
Gemfile.lock

`csv` and `base64` are loaded from the standard library, but will no longer be part of the default gems in the future versions of Ruby.
Add `csv` and `base64` gems
Warnings disappear

Add base64 and cvs gems

---

assets/stylesheets/_screen.scss
assets/stylesheets/pages/_swift-evolution.scss

Sass's behavior for declarations that appear after nested rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in `& {}`.
Fixed the deprecations above
Deprecations are not there anymore

Fix Sass deprecations

---

_posts/2024-08-16-introducing-swift-nio-oblivious-http.md
_posts/2024-08-21-introducing-swift-nio-oblivious-http.md

Motivation:
Apple has released another library to the open source - the world might want to know.
Modifications:
Add a new blog post file.
Result:
Blog post announcing this new open source library has gone live.

Blog post announcing swift-nio-oblivious-http

---

documentation/cxx-interop/index.md

This is interesting for reverse interop where the Swift functions take or return foreign reference types.

[cxx-interop] Document the calling conventions for C++ FRTs

---

documentation/articles/getting-started-with-vscode-swift.md

The Creating a New Swift Project instructions was missing a step indicating what command to run from the command pallette to create a new project.

Add missing step to Getting Started with VS Code docs

---

documentation/cxx-interop/index.md

This adds `SWIFT_MUTATING`, `SWIFT_NONCOPYABLE` to the list of supported customization macros.

[cxx-interop] Document new macros from `<swift/bridging>` header

---

contributor-experience-workgroup/index.md

Add new workgroup members, James Dempsey and Joseph Heck.

Update membership of Contributor Membership Workgroup

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for September.

Updated Community Showcase packages for September

---

contributor-experience-workgroup/index.md

Add emeritus member section to page along with first emeritus member
Also consolidate membership information paragraphs
The new section uses the same format and wording as the emeritus member sections of other workgroups.

Add emeritus member to Contributor Experience page

---

_data/builds/swift_releases.yml
_includes/install/_build_release.md
install/linux/amazonlinux/2/index.md
install/linux/debian/12/index.md
install/linux/fedora/39/index.md
install/linux/ubi/9/index.md
install/linux/ubuntu/20_04/index.md
install/linux/ubuntu/22_04/index.md
install/linux/ubuntu/24_04/index.md
install/windows/index.md

This PR implements a generic way of detecting multiple archs for the latest release, and add Swift on Windows (arm64) to `swift_releases.yml`.
`_includes/install/_build_release.md` was relying on a dedicated `include.aarch64` argument for generating an additional link. This is error-prone (eg. we may forget to specify the argument even if an aarch64 toolchain exists), not extensible (eg. if we want to add `riscv64` support we'll then need a new dedicated link) and not future proof (eg. if a new platform doesn't support `x86_64` we'll need a bunch of extra logic).
`_includes/install/_build_release.md` was partially refactored that:
- drops the `aarch64` input argument;
- detects available archs directly from `swift_releases.yml`;
- removes all special treatment for x86_64 and use unified …

Improve multi-arch links detection by a generic solution and add Windows (arm64) to 6.0 release

---

platform-steering-group/index.md

Removing the broken url from platform steering group page: https://www.swift.org/charter-drafts/steering-group.md
Github issue: https://github.com/swiftlang/swift-org-website/issues/765

Removed a broken link in the platform steering group page

---

_data/builds/swift_releases.yml
_includes/install/_build_release.md
install/windows/index.md

hub.docker.com images are now available.

[6.0] Add Docker images to the install page

---

_includes/install/_build_release.md
_includes/install/_static_sdk_release.md
install/macos/index.md

#742 broke the styling for the static Linux SDK cards.
- Updated the static Linux SDK cards to use the new styling
|Before|After
|---|---|
|![CleanShot 2024-09-18 at 09 37 18](https://github.com/user-attachments/assets/6147cde4-ff2a-4239-b3fd-246881f6ec0c)|![CleanShot 2024-09-18 at 09 37 01](https://github.com/user-attachments/assets/b29eec8b-fad7-4fb8-b864-41112f8edd48)|
|Before|After
|---|---|
|![CleanShot 2024-09-18 at 09 38 06](https://github.com/user-attachments/assets/6ef9bd6c-6897-4052-b22d-f7b291b1b125)|![CleanShot 2024-09-18 at 09 38 22](https://github.com/user-attachments/assets/484db929-cbbf-4c13-88cf-14155679383e)|
|Before|After
|---|---|
|![CleanShot 2024-09-18 at 09 39 23](https://github.com/user-attachments/assets/d1cbb0e9-cc85-461c-81aa-9cffd38135dc)|![CleanShot 2024-09-18 …

Fix static Linux SDK card styling in install

---

language-steering-group/index.md

There should only be a single H1 per page. It also applies the wrong hierarchical styling.
- Changed the Charter H1 to an H2
|Before|After
|---|---|
|![CleanShot 2024-09-18 at 09 57 05](https://github.com/user-attachments/assets/c987f734-3b3b-46b9-8820-09fc292b1e4e)|![CleanShot 2024-09-18 at 09 57 25](https://github.com/user-attachments/assets/5c7b4f80-0a29-43da-9e84-31994a2fa909)|

Fix two H1 tags on language steering group page

---

documentation/cxx-interop/status/index.md

This adds a note in the C++ interop docs about the minimum supported C++ standard.

[cxx-interop] Document the C++14 requirement

---

_data/contributer-experience-workgroup/emeriti.yml
_data/contributer-experience-workgroup/members.yml
_data/language-steering-group/members.yml
_data/platform-steering-group/members.yml
contributor-experience-workgroup/index.md
language-steering-group/index.md
platform-steering-group/index.md

Refactoring the hardcoded members list into yml file on platform steering group page: https://www.swift.org/platform-steering-group/

Fixed platform steering group membership

---

documentation/cxx-interop/index.md

Fix incorrectly referring to "structure" instead of "class" in a section of C++ interoperability documentation.
Under [Using Swift Classes in C++](https://www.swift.org/documentation/cxx-interop/#using-swift-classes-in-c), the documentation is incorrectly referring to the Swift "structure" instead of "class".
Replace the Swift "structure" with "class".
Before:
> Swift classes that are exposed to C++ become C++ classes in the generated header. Top-level classes are placed in the C++ `namespace` that represents the Swift module. The exposed initializers, methods and properties defined inside of the Swift structure become members of the C++ class.
After:
> Swift classes that are exposed to C++ become C++ classes in the generated header. Top-level classes are placed in the C++ `namespace` …

[cxx-interop] Fix incorrectly referring to "structure" instead of "class"

---

_data/foundation-workgroup/members.yml
_data/navigation.yml
foundation-workgroup/index.md

This change adds the charter of the already established Foundation Workgroup at swift.org/foundation-workgroup.

Add foundation workgroup charter

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for October.

Updated Community Showcase packages for October

---

documentation/articles/zero-to-swift-nvim.md

`cmp.visual()` should be `cmp.visible()`

Fix typo in Zero to Swift Neovim

---

community/_forums.md

The Core Team has decided to institute a policy against expressive images, such as memes, in forum posts.  This has been announced on the forums; link to it from the official forums guidelines.

Link to the new policy banning memes from the forums

---

install/windows/_scoop.md
install/windows/_winget.md
install/windows/scoop/index.md
install/windows/winget/index.md

Instruct users to install the MSVC ARM64 tools when installing Visual Studio. This should ensure that cross-compilation is possible (and native compilation when on ARM64).
Fixes: #839

Windows: add ARM64 MSVC Tools to VS installation

---

install/windows/_scoop.md
install/windows/_winget.md
install/windows/scoop/index.md
install/windows/winget/index.md

Reduce inconsistencies between the various Windows pages around installing the VS dependencies. Also include a link to the VS editions page to make sure that it's clearer when you need to install a paid SKU.

Harmonize VS Dependency language across Windows install pages

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

Merge after #858.
This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for December.

Updated Community Showcase packages for December

---

_data/builds/swift_releases.yml
_includes/install/_old-release.html
_includes/install/_older-releases.md
_includes/install/_static_sdk_release.md
install/macos/_old-release.html
install/macos/_older-releases.md

Older release view now contains a link to copy the static sdk command:

Swift 6.0.3 Release

---

_includes/install/_linux_platforms_tabs.md
install/macos/index.md

Correct the swiftly download URLs

Swiftly preview

---

_data/server-workgroup/projects.yml

As refer the PR https://github.com/swiftlang/swift-org-website/pull/868 of @0xTim . I have a minor enhance that appends `.git` for SwiftASN1's URL that will be consistent with other URLs.
Appends `.git` for SwiftASN1's URL that will be consistent with other URLs.
+ _data/server-workgroup/projects.yml
That will be consistent with other URLs in `projects.yml`

Append `.git` for SwiftASN1's URL  at projects.yml

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for January.

Updated Community Showcase packages for January

---

_data/builds/swiftly_release.yml
api/v1/swiftly.json

As pitched in the forum this is a preliminary API providing metadata about the currently available swiftly release. https://forums.swift.org/t/new-swift-org-api-endpoint-for-the-current-swiftly-release/74702
Swiftly itself has a self-update mechanism to help provide an easy path to keep in sync with the capability of the swift.org website, and to roll out new features and bug fixes. Since swift.org is the place where the official swiftly releases will be published then this API is updated whenever there is a new release. Since there has not yet been a swiftly release on swift.org and existing swiftly installations do not yet use this new API mechanism, there are no expected clients of this API yet. This is a preliminary step to prepare for a release of swiftly when that does happen.
Added …

Add placeholder API for swiftly releases

---

openapi/TestSwiftOrgClient/Package.swift
openapi/TestSwiftOrgClient/openapi-generator-config.yaml
openapi/TestSwiftOrgClient/swiftorgClient/Tool.swift
openapi/index.md
openapi/swiftorg.yaml

A new Swiftly releases API was added in https://github.com/swiftlang/swift-org-website/pull/828, but that happened before the first OpenAPI PR landed in https://github.com/swiftlang/swift-org-website/pull/841.
The `/sswg/incubation/...` API was also undocumented.
Add the Swiftly and SSWG APIs info into the existing OpenAPI doc, allowing Swiftly and other API adopters to generate their client.
Quicker, less error-prone integration with the Swift.org API from tools in the ecosystem.

[OpenAPI] Document the Swiftly and SSWG APIs

---

getting-started/embedded-swift/index.md

Without Xcode installed and selected, running `export TOOLCHAINS` has no effect on macOS.
rdar://131600948

Mention Xcode as required on macOS in `getting-started/embedded-swift`

---

install/macos/index.md

When cross-compiling on macOS to non-Darwin platforms (Linux or Embedded Swift), `.pkg` installer is required, as it provides necessary tools and has more LLVM backends enabled.
https://www.swift.org/install/macos/ page now clarifies which installation methods are suitable for each of the use cases.
There's less confusion about versions of toolchains necessary for cross-compilation to non-Darwin platforms.

Clarify that `.pkg` installer is required for cross-compilation

---

install/linux/tarball/index.md

The instructions provided are incorrect: in recent Swift versions the `swift` command won't run the REPL and users need to execute `swift repl` explicitly. Additionally, on non-Darwin platforms users build Swift packages not "Swift projects", the `swift build` command should be utilized for that.

Fix REPL and build instructions in `install/linux/tarball`

---

_data/website-workgroup/emeriti.yml
_data/website-workgroup/members.yml

Paris left the WWG :-(
Remove Paris from the WWG page
Paris doesn't show in the WWG page

Remove Paris from WWG

---

platform-support/_platform-support.md

We no longer support CentOS 7, but the platform support page says we do. The page doesn't mention Debian or Fedora either, which we have images for. Replace the references of CentOS 7 with references to Fedora and Debian.
The current content is inaccurate and I'm getting asked about it.
Replaced inaccurate content with relevant information.
The website will have fewer inaccuracies.

Replace CentOS with Fedora and Debian

---

_data/authors.yml
_posts/2025-02-01-the-next-chapter-in-swift-build-technologies.md

Add blog post about [Swift Build](https://github.com/swiftlang/swift-build), a new Swift open source project just announced at FOSDEM.
Add blog post: "The Next Chapter in Swift Build Technologies"

New Post: The Next Chapter in Swift Build Technologies

---

documentation/continuous-integration/index.md

Fixes #884 
- Fixed two links on the page
- No more broken links! 🙂

Fix broken links on Swift Continuous Integration page

---

_includes/install/_linux_platforms_tabs.md
install/macos/index.md

This is against the existing draft PR for adding Swiftly install options. This puts Swiftly alongside Xcode instead of the Pkg install for Mac OS, and as the primary option, alongside Docker, for Linux.

Update swiftly install pages

---

.github/workflows/ci.yaml
docker-compose.yaml
openapi/TestSwiftOrgClient/Shared/Tester.swift
openapi/TestSwiftOrgClient/downloadswiftorgClient/Issue847Workaround.swift
openapi/TestSwiftOrgClient/downloadswiftorgClient/Tool.swift
openapi/TestSwiftOrgClient/swiftorgClient/Tool.swift
openapi/downloadswiftorg.yaml
scripts/soundness.sh

First steps for adopting GH actions with an action to run on PRs to make sure the site works. This runs:
* the soundness script (which has already picked up an error)
* `jekyll build`
* The OpenAPI test client to ensure the OpenAPI spec works (cc @czechboy0)
@shahmishal can we can actions enabled? I don't know what the original CI was doing, I'm assuming just a Jekyll build

Add GH Action for CI

---

gsoc2025/index.md

Idea from last year, carried over by @xedin

[gsoc2025] add property wrappers to macros project

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for February.

Updated Community Showcase packages for February

---

gsoc2025/index.md

The only valid project length are 90, 175 and 350 -- this fixes projects which were picking not exactly those lengths.

Fix project hours in gsoc 2025

---

gsoc2025/index.md

Add a GSoC 2025 project idea titled "Improved console output for Swift Testing".

GSoC 2025 project idea: Improved console output for Swift Testing

---

gsoc2025/index.md

This adds a "Improved command line tool documentation" project idea to the GSoC page. 
This adds a project idea for GSoC about improved documentation for Swift command line tools. The Documentation Workgroup talked about this project idea in the most recent meeting.
This adds a project idea for GSoC about improved documentation for Swift command line tools. 
The new project idea is listed at the bottom of the GSoC 2025 page.

Add "Improved command line tool documentation" project idea for GSoC

---

gsoc2025/index.md

This adds a "Documentation coverage" project idea to the GSoC page. 
This adds a project idea for GSoC about emitting and displaying documentation coverage information. The Documentation Workgroup talked about this project idea in the most recent meeting.
This adds a project idea for GSoC about documentation coverage.
The new project idea is listed at the bottom of the GSoC 2025 page.

Add "Documentation coverage" GSoC project idea

---

gsoc2025/index.md

This change adds a "OpenAPI integration with DocC" project idea to the GSoC page.
The Swift ecosystem already offers tooling for OpenAPI. This project explores expanding that support by incorporating DocC for OpenAPI documentation.
Project added to the list of GSoC ideas.
New project on the GSoC25 list page.

Add "OpenAPI integration with DocC" GSoC project idea

---

_posts/2022-07-14-vscode-extension.md

Fixup the link now that vscode-swift has moved to swiftlang.

Fix vscode-swfft Create Issue link

---

_data/builds/swiftly_release.yml

Now that the swiftly 0.4.0 release has been published, update the swiftly_release API to the new version.

Update swiftly release to 0.4.0

---

community/index.md
contributing/_contributing-code.md

We currently have three roles that contributors to the Swift project on GitHub can have: Everybody can participate the Swift open source project and become a *Contributor*. After creating a track record by creating 5 non-trivial pull requests that were accepted without modifications, contributors can request [*Commit Access*](https://www.swift.org/contributing/#commit-access), which allows them to merge PRs and also trigger CI. Finally, contributors can become [*Code Owners*](https://www.swift.org/community/#code-owners).
With the current structure, gaining the ability to trigger CI has quite a high bar and hinders new contributors from accelerating their contributions to Swift. We are thus introducing a new role: After contributing to Swift multiple times, contributors can request to …

A new Member contributor role that can trigger CI

---

_data/documentation.yaml
documentation/monthly-non-darwin-release/index.md

Monthly non-darwin release process

---

contributing/_contributing-code.md

While at it, also improve the phrasing of the requirements slightly.

Clarify Nomination for the Member role

---

install/macos/package_installer/index.md

Current macOS installation instructions recommend using a global system path instead of home user directory, which may require admin privileges that aren't always available. Additionally, it assumes that a multi-step installer GUI will run, but no guidance for that installer is provided.
We should prefer installing into user's home directory and provide instructions that require as little manual intervention as possible.
A CLI command is listed that automatically installs into user's home directory, not requiring admin privileges, and also avoid running a multi-step GUI installer.
Instructions are easier to run and require less manual steps.

Provide installation CLI command on `package_installer` page

---

_data/navigation.yml
_data/testing-workgroup/members.yml
community/index.md
testing-workgroup/index.md

This PR adds a charter for the Testing Workgroup, and links to it from the site-wide navigation. The membership YAML file is a placeholder initially but I plan to fill this in shortly before landing the PR once accepted.

Add charter for the Testing Workgroup

---

install/macos/package_installer/index.md

Completes the installation path update started in #922.
Changed the toolchain path in documentation from:
`/Library/Developer/Toolchains/<toolchain name>.xctoolchain` 
to 
`~/Library/Developer/Toolchains/<toolchain name>.xctoolchain`
Ensures full consistency with #922. The toolchain path now correctly matches the actual installation location.

Fix path for TOOLCHAINS environment variable in `package_installer` page

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for March.

Updated Community Showcase packages for March

---

openapi/TestSwiftOrgClient/swiftorgClient/Tool.swift
openapi/swiftorg.yaml

When using the current OpenAPI specification for discovering snapshot toolchains
in an OpenAPI generator, there is a code-level limitation on the known branches
(e.g. main or 6.0), and the known platform identifiers (e.g. macOS, amazonlinux2).
These values will change over time and new snapshot branches come (e.g. 6.1, or 7.0)
and platforms are added (e.g. "ubuntu2404"). Clients that are based on earlier versions
of the schema should remain compatible, and permit user input of new values that they
know to exist. That's not possible currently.
This change will adjust the schema to take advantage of the schema types that allow a
choice of a known value, and ones that are not (yet) known to the schema.

Permit freeform source branch and platform identifiers in OpenAPI spec

---

_includes/install/_linux_platforms_tabs.md
install/linux/swiftly/index.md
install/macos/index.md
install/macos/swiftly/index.md

The macOS installer puts swiftly in a different location now that's more understandable.
Update the instructions to reflect the new install location for the macOS packages.
In order to guarantee that the environment file is in the expected location, set the swiftly
environment variables to default to those location on both macOS and Linux.

Update swiftly install one-liner and instructions

---

assets/stylesheets/elements/_grid.scss

Issue: https://github.com/swiftlang/swift-org-website/issues/941
Changed box overflow

#941 - Fix macOS and Linux pages mobile resize

---

install/macos/index.md

Only swift.org toolchains support Static Linux SDK, which is currently not made clear in the description on this page.

Clarify Static Linux SDK support in `install/macos/index.md`

---

_data/builds/swift-6_1-branch/static_sdk.yml

As I commented [here](https://github.com/swiftlang/swift-org-website/commit/018ca4354ef294a4d6fd74418f1cb7b97908b7b9#r153827504), a signature file of Static Linux SDK for Swift 6.1 has not available for download lately.
Download page: https://www.swift.org/install/macos/
The reason is that those URLs are wrong.
```console
$ curl https://download.swift.org/swift-6.1-branch/static-sdk/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-25-a/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-25-a-a_static-linux-0.0.1.artifactbundle.tar.gz.sig
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Error><Code>404</Code><Message>No message</Message><RequestId>d277fed7-878a-4468-8301-81b07128bbb5</RequestId></Error>
$ curl https://download.swift.org/swift-6.1-branch/static-sdk/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-25-a …
```

Fix typos in Static Linux SDK Signature URLs

---

api/v1/install/dev/6.1/debian12.json
api/v1/install/dev/6.1/fedora39.json
api/v1/install/dev/main/debian12.json
api/v1/install/dev/main/fedora39.json

Added support for Debian 12 and Fedora 39 to swift.org API for 6.1 and main branch
This change allows running `swiftly install main-snapshot` and `swift install 6.1-snapshot` on Debian 12 and Fedora 39. This was possible in previous versions of swiftly.
I added support for Debian 12 and Fedora 39 to swift.org API for 6.1 and main branch.
The referenced data already exists.
- `site.data.builds.swift-6_1-branch.debian12`: https://github.com/swiftlang/swift-org-website/blob/main/_data/builds/swift-6_1-branch/debian12.yml
- `site.data.builds.swift-6_1-branch.debian12-aarch64`: https://github.com/swiftlang/swift-org-website/blob/main/_data/builds/swift-6_1-branch/debian12-aarch64.yml
- `site.data.builds.swift-6_1-branch.fedora39`: https://github.com/swiftlang/swift-org-website/blob/main/_data/b …

[API] Add support for Debian 12 and Fedora 39 for 6.1 and main branch

---

api/v1/install/dev/6.1/windows10.json
api/v1/install/dev/main/windows10.json

Added support for Windows arm64 to swift.org API for 6.1 and main branch
I added support for Windows arm64 to swift.org API for 6.1 and main branch.
The referenced data already exists.
- `site.data.builds.swift-6_1-branch.windows10-arm64`: https://github.com/swiftlang/swift-org-website/blob/main/_data/builds/swift-6_1-branch/windows10-arm64.yml
- `site.data.builds.development.windows10-arm64`: https://github.com/swiftlang/swift-org-website/blob/main/_data/builds/development/windows10-arm64.yml
The `arm64` fields will be added to the following endpoints.
- https://www.swift.org/api/v1/install/dev/6.1/windows10.json
- https://www.swift.org/api/v1/install/dev/main/windows10.json

[API] Add support for Windows arm64 for 6.1 and main branch

---

README.md
docker-compose.yaml

Since Compose V2, `docker-compose` has been deprecated, and instead, `docker compose` has been recommended.
https://docs.docker.com/compose/releases/migrate/#docker-compose-vs-docker-compose

Replace deprecated `docker-compose` with `docker compose` in the instructions

---

_posts/2025-03-31-swift-6.1-released.md

I proposed a fix for the missing space [here](https://github.com/swiftlang/swift-org-website/pull/939#discussion_r2019785899), but it seems to have been overlooked.
Also, thanks to @AliMark71 for [calling out](https://github.com/swiftlang/swift-org-website/pull/939#discussion_r2021827252) some repeated words.
- Add missing space
- Remove repeated words
🧹

6.1 blog post fixes

---

documentation/server/guides/memory-leaks-and-usage.md

remove incorrect suggestion and direct to section that details the process using swift build and ASAN_OPTIONS set
Thread on the Open Source slack highlighted some confusion around the existing documentation. The correct documentation is there, but wasn't referenced.
Removes the incorrect suggestion (`-sanitize=leaks`) and replaces it with a reference to the correct documentation.
For more information... link to the correct section.
(resolves rdar://148594440)

correct address sanitizer reference in server guide 

---

_includes/install/_linux_platforms_tabs.md

The current shell script does not work for zsh resulting in the following error.
```
zsh: parse error near `)'. 
```
Adding quotes around the file name fixes the command for bash and zsh. Tested locally.
Install command works for zsh and bash.

Fix linux install command for zsh shell.

---

gsoc2025/index.md

The project size for the DocC language features says medium, but lists a 90 hour completion time. Adjust this to 175 hours to be in line with a medium project size.

fix project size for DocC language features GSoC project idea

---

_data/server-workgroup/members.yml

- remove affiliation for Simon 
- change Josh and Seb's affiliation from Amazon to AWS
Modified the `_data/server-workgroup/members.yml` 
This page at https://www.swift.org/sswg/ is updated

[SSWG] Remove affiliation for Simon and use AWS for Josh and Seb

---

documentation/tspl/index.md

The Chinese translation website URL needs to be updated to reflect the current location of the Swift programming language documentation in Chinese. This change ensures that Chinese-speaking developers can access the most up-to-date translation resources.
- Updated the Chinese translation website URL from the old link to `https://doc.swiftgg.team`
After this change, Chinese-speaking developers will be directed to the correct and current URL for accessing the Swift programming language documentation in Chinese. This improves the accessibility of Swift documentation for the Chinese developer community.

Updated Chinese translation URL.

---

openapi/swiftorg.yaml

This field is present in platform objects representing

Add OpenAPI checksum field to Platform for static SDK objects

---

_includes/install/_linux_platforms_tabs.md
install/macos/index.md

When SWIFTLY_HOME_DIR is set then swiftly will put the environment script in
that location. Fix the website scripts to accommodate the case where the environment
variable is already set.

Fix swiftly shell scripts for case where SWIFTLY_HOME_DIR is set

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for May.

Updated Community Showcase packages for May

---

assets/stylesheets/new-stylesheets/pages/_install.scss
install/linux/index.md
scripts/copy-vendor.sh
scripts/prettify.sh

There are a couple of style issues:

Fix mobile code box and link callout

---

_data/new-data/get-started/cloud-services/headline-section.yml
_data/new-data/get-started/cloud-services/hero.yml
_data/new-data/get-started/cloud-services/secondary-content.yml
_data/new-data/get-started/cloud-services/tertiary-content-cloud-native.yml
_data/new-data/get-started/cloud-services/tertiary-content.yml
get-started/cloud-services/index.md

Updates the copy on the Cloud Services use case page.

Update copy on cloud services use case page.

---

_data/new-data/install/linux/releases.yml
_data/new-data/install/macos/releases.yml
install/linux/index.md
install/macos/index.md

For Swiftly installation we need to add the Fish command
Tab and command are added for Linux and macOS

Add Fish for Swiftly install

---

_data/new-data/footer/main-navigation.yml
_includes/new-includes/footer/footer.html
_includes/new-includes/footer/navigations/main.html
assets/stylesheets/new-stylesheets/includes/footer/_base.scss
assets/stylesheets/new-stylesheets/includes/footer/_mobile.scss

It's good UX to include the main navigation links in the footer as well. For reference, see [this article on "Doormat Navigation"](https://www.nngroup.com/articles/footers/#toc-doormat-navigation-5).
- Adds the main navigation links to the footer
- I vertically centered the navigation titles (Tools, Community, Governance) with the Swift logo on desktop to make this look as balanced as possible
- ❓ I'm wondering if we maybe need a bit more margin between the logo and the links on desktop
- Restructures the code slightly to allow for this — feel free to suggest improvements here!
|Before (desktop)|After (desktop)|
|---|---|
|![CleanShot 2025-05-29 at 09 36 11](https://github.com/user-attachments/assets/730af049-ee11-496a-ab13-be11f8fc4ef9)|![CleanShot 2025-05-29 at 09 36 …

Add main nav links to footer

---

assets/stylesheets/new-stylesheets/includes/callout/_base.scss

Adds an underline to links in callout blocks to make it more obvious that they are links.
It's really difficult to tell that there are two links here.
For UX reference, see [Affordances](https://www.interaction-design.org/literature/topics/affordances?srsltid=AfmBOopeHGmxus01yzPd3j_4HIPU5eOO4iUBlYG66-PuYCpXr5-x5ssE#what_are_affordances?-0).
> Affordances are the characteristics or properties of an object that suggest how it can be used. It shows a user that an object can be interacted with.
Currently, there are no affordances on these links other than the verb in the text suggesting an action.
This PR adds an underline to the links to make them appear more like links.
Notes:
* I decided to not add a hover effect as we don't have that elsewhere either
* We may want to look over other links …

Add underline to callout links

---

_includes/new-includes/components/card-grid.html

Remove some TODO code from a component

---

assets/stylesheets/new-stylesheets/pages/_get-started.scss

Fixes broken code block tabs.
The code block tabs don't work properly on mobile:
* On the install page, the Fish tab is not visible
* On the CLI tools page, it doesn't scroll all the way to the last item.
- Fixed the width of the tabs
- I'm not sure what the negative 59px was for?
|Before|After|
|---|---|
|![CleanShot 2025-06-04 at 22 08 14](https://github.com/user-attachments/assets/89017e90-4192-4e93-b3b8-060488fac01a)|![CleanShot 2025-06-04 at 22 08 22](https://github.com/user-attachments/assets/68f96a5f-7901-479d-a6dd-5f8470af5eaa)|
|Before|After|
|---|---|
|![CleanShot 2025-06-04 at 22 08 02](https://github.com/user-attachments/assets/ae958fcf-07e7-4ed8-be3b-abd3f8463411)|![CleanShot 2025-06-04 at 22 07 32](https://github.com/user-attachments/assets/e8ac8f3c-a026-418c-877a-4d9749b87d7 …

Fix code block tabs on mobile

---

assets/stylesheets/new-stylesheets/_helpers.scss
assets/stylesheets/new-stylesheets/includes/callout/_base.scss
assets/stylesheets/new-stylesheets/pages/_install.scss

Add helper mixin for underline and use on install page too.
We have a "fancy" underline on the landing page. We should use this on the install page as well for consistency.
- Added a `mixin` that can be used using `@include`
- Use it on the landing page
- Use it on the install page
|Before|After|
|---|---|
|![CleanShot 2025-06-04 at 22 17 49](https://github.com/user-attachments/assets/2d7ff1ec-e0af-4561-8e07-bf88745096aa)|![CleanShot 2025-06-04 at 22 17 31](https://github.com/user-attachments/assets/9c2312f2-ed21-46ff-91dd-76a4c5cfee5f)|

Use fancy underline on install page as well + create helper mixin

---

_layouts/new-layouts/base.html
assets/javascripts/new-javascripts/color-scheme-toggle.js

When a user refreshes the page in dark mode, the light styles flash before being set to dark. 
I moved the function call to set the theme from the `DOMContentLoaded` event to directly after the opening body tag. This avoids loading the light styles before the data attribute is set. 
Light styles no longer flash on load in dark mode.

Fix: Light Styles Flash in Dark Mode

---

_data/new-data/install/linux/dev.yml
_includes/new-includes/components/linux-releases.html
_includes/new-includes/components/static-linux-sdk-dev.html
_includes/new-includes/components/wasm-sdk-dev.html
install/linux/index.md
install/macos/index.md

I added support for nightly snapshots via swiftly. Additionally, I added a section for static SDK and WASM SDK on the Linux and macOS install page.

Add support for Wasm sdk support

---

_data/new-data/install/windows/releases.yml
install/linux/index.md
install/windows/index.md

We are currently missing editor information on the install page for Windows and Linux. This change will highlight the Swift extension for VSCode on the Windows and Linux pages.

[Install] Include VSCode IDE info on the Windows and Linux install page

---

documentation/cxx-interop/safe-interop/index.md

99% of this document is taken from Gabor's PR: https://github.com/swiftlang/swift-org-website/pull/958.

[cxx-interop] Add initial documentation for strict memory safety

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This update contains the [Community Showcase packages](https://www.swift.org/packages/showcase.html) for June.

Updated Community Showcase packages for June

---

documentation/cxx-interop/index.md

This adds a publicly visible link to the new safe interop documentation from the main C++ interop documentation page.

[cxx-interop] Add link to safe interop documentation

---

documentation/articles/wasm-getting-started.md

The installation page no longer lists checksums directly, but provides "Copy install command" buttons.
"Wasm Getting Started" guide is updated accordingly directing users to "Copy install command" button instead of checksums.
We avoid possible confusion caused by the mismatch between the guide and new website design.

Clarify installation command in `wasm-getting-started.md`

---

documentation/articles/wasm-getting-started.md

Embedded Swift Concurrency is not generally available yet in latest development snapshots, as we're working on resolving remaining issues.
Embedded Swift Concurrency should not be mentioned in the Wasm getting started guide until all blocking issues are resolved. The guide also should link to corresponding documentation page to clarify the subset of the language available.
Features available in Embedded Swift for Wasm are more clearly specified.

Clarify available Embedded Swift features in `wasm-getting-started.md`

---

documentation/core-libraries/_foundation.md
documentation/core-libraries/_swift-testing.md
documentation/core-libraries/_xctest.md
documentation/core-libraries/index.md

Update the Swift Core Libraries page for Swift Testing and new Swift Foundation.
The Core Libraries page was missing Swift Testing, and the Foundation section wasn't updated for Swift 6's new Swift Foundation.
- Add a new Swift Testing section in the Core Libraries page
- Update the Foundation section in the Core Libraries page
The Swift Core Libraries page is updated with the latest libraries.

Update Core Libraries page

---

CODEOWNERS

Add 'heckj' to reviewers for pull requests
Having joined the workgroup, adding my GitHub handle to be able to provide reviews for existing pull requests.
Updated CODEOWNERS 
Will be able to provide reviews for pull requests

adds 'heckj' to reviewers sets to be able to review pull requests

---

documentation/cxx-interop/safe-interop/index.md

This adds documentation around __counted_by, __sized_by, API notes, and using lifetime attributes in C.
This is stacked on top of https://github.com/swiftlang/swift-org-website/pull/980.

Safe c interop

---

_includes/install/_old-release.html

There are two definitions of `copyToClipboard` in the codebase, one with one arg
and one with two args. The onClick handler ends up calling the wrong one for a
number of links. I assume the issue is something like:
- Both definitions end up being defined on the same page
- The onClick ends up getting the one with two args when it expects the one with one arg.
Attempt to fix this by instead using the two arg version and removing the one arg version.
However I do not have a Ruby environment setup to test with so I haven't been able to try it.
This resolves https://github.com/swiftlang/swift-org-website/issues/1108.

Fix "Copy install command" button on old releases page

---

api/v1/install/dev/6.2/static-sdk.json
openapi/swiftorg.yaml

Fix static-sdk JSON API for 6.2 branch
- [Static SDKs JSON API](https://www.swift.org/api/v1/install/dev/6.2/static-sdk.json) returns `null` for 6.2 branch.
- OpenAPI spec doesn't include branch 6.2 so tests don't catch this.
- Fixed the yaml data source path of the JSON API.
- Added branches 6.1, 6.2 to OpenAPI spec.
- `/api/v1/install/dev/6.2/static-sdk.json` returns a valid value.
- [Local test](https://github.com/swiftlang/swift-org-website/tree/main/openapi/TestSwiftOrgClient#usage) now also tests branches 6.1, 6.2 and passes.

Fix static-sdk JSON 6.2 API

---

_data/packages/packages.yml
_data/packages/showcase-history.yml

This is a follow-up to #1113. Android and Wasm are not officially supported yet, so removing the compatibility status for them for now. This will be re-added in a future update once the platforms are supported.

Fixed up package compatibility to only focus on supported platforms

---

_data/server-workgroup/members.yml
_info-architecture/0001-swift-information-architecture-project.md
_posts/2020-09-16-swift-5.3-released.md
documentation-workgroup/index.md

when i got it changed by court order earlier this year, i settled on the spelling *Diana* (with one *n*), which is what i now use on all my legal documents. so i would like the spelling used in this repo to match
updated occurrences of `Dianna` to `Diana`

update spelling of my name

---

_data/authors.yml
documentation/articles/static-linux-getting-started.md

- Enhance clarity and transparency by adding more details about dependency management when using the Static Linux SDK, especially regarding the dependencies bundled with it.
- Add a comment contrasting the Linux SDK with Apple platforms.
These changes are the result of a collaboration between @al45tair, @etcwilde, and me.

[static-linux-sdk] Update "Getting Started with the Static Linux SDK"

---

getting-started/library-swiftpm/index.md

This updates the [Swift Package Manager "Getting Started" page](https://www.swift.org/getting-started/library-swiftpm/) to showcase usage of Swift Testing instead of XCTest.
In conjunction with this changes to the website content, I am updating the linked example package repo in https://github.com/swiftlang/swift-getting-started-package-library/pull/4.
Swift Testing is generally recommended over XCTest now for new packages.
- Update the test file to replace XCTest usage with analogous Swift Testing test code.
- Update the example console output to emphasize Swift Testing.
The article now shows Swift Testing.

Showcase usage of Swift Testing instead of XCTest in package manager "Getting Started" article

---

_data/new-data/get-started/cloud-services/tertiary-content-cloud-native.yml
_data/new-data/get-started/cloud-services/tertiary-content.yml

The order of the server packages was a bit arbitrary. This PR re-orders them by sorting them from highest to lowest level, for their respective importance and then how production ready they are.

Re-order the server packages

---

_data/new-data/get-started/cloud-services/link-columns.yml

Resolving possible oversight - linking to newer content on building a web server with Vapor from the documentation panel  (link columns)

link from the documentation set into the new guide for building a vapor web server

---

_includes/install/_windows_dependencies.md
install/windows/_manual.md
install/windows/_windows.md
install/windows/manual/index.md

Update the install instructions to use Python 3.10.
https://github.com/swiftlang/swift/pull/83929 updated the Windows toolchain to use Python 3.10.1. Python 3.10.x is now required to use lldb on Windows.
Update the install instructions to use Python 3.10 instead of 3.9.
Users will be instructed to install Python 3.10 instead of 3.9.
rdar://159596578

[windows] update the install instructions to use Python 3.10

---

_includes/install/_windows_dependencies.md
install/windows/_manual.md
install/windows/_windows.md
install/windows/manual/index.md

This reverts https://github.com/swiftlang/swift-org-website/pull/1140.
We should remerge the original patch once `6.2.1` is released.

Revert "[windows] update the install instructions to use Python 3.10 (#1140)

---

contributing/_contributing-code.md

Following the introduction of the *Member* role, restructure the *Committer* role to align more closely with the structure of the *Member* role. While doing this, also make a couple of tweaks to the role:
- Rename the role from *Commit Access* / *Committer* to *Code Merger*
- Slight change in phrasing for the requirements specifying *small to medium-sized, non-trivial, high-quality* and allowing *little guidance* instead of *accepted without modifications*
- *Code Merger* can be granted on a per-repository basis instead of the current *Commit Access* role, which is phrased as giving commit access to all repos at the same time.
There has been a lot of discussion around the naming of this role. Names that we have rejected are:
- *Approver*: Same reason as *Reviewer*.
- *Collaborator*: …

Rephrase the `Committer` role

---

_data/new-data/blog/page-data.yml
_layouts/new-layouts/post.html
_posts/2024-09-17-announcing-swift-6.md
_posts/2025-06-04-redesigned-swift-org-is-now-live.md
assets/stylesheets/new-stylesheets/pages/_post.scss

We had to make some changes for consistency between posts (example: featured images)
- Added feature images
- Adjustments on layout

Updates blog details

---

assets/stylesheets/new-stylesheets/pages/_blog.scss

Removes default disabled input styles that are currently being applied on Safari. 
Adds CSS rule to remove background style. 
Background style is removed from disabled inputs.

style(blog-page): remove disabled background styles.

---

openapi/TestSwiftOrgClient/swiftorgClient/Tool.swift
openapi/swiftorg.yaml

The Swift.org OpenAPI doc was missing newer platforms, Swift versions, and fields added recently.
- Added the `docker` field in the releases array, pointing to the container tag
- Added enum cases for the Static and WASM SDKs for toolchain types
- Added `debian12`, `fedora39`, `ubuntu2404` to the list of platforms that toolchains exist for
- Added/updated some example values
More up-to-date OpenAPI doc, useful to tools like swiftly and others who generate code from the OpenAPI doc.

OpenAPI doc updates for Swift 6.2

---

documentation/articles/wasm-getting-started.md

`wasm-getting-started.md` needs an update for 6.2 release
Updated the copy to use 6.2 release instead of development snapshots.
The article is up to date for 6.2 release.

Update `wasm-getting-started.md` for 6.2 release

---

documentation/articles/wasm-getting-started.md

After https://github.com/swiftlang/swift-org-website/pull/1162 this clause is no longer needed.

Remove outdated wording in `wasm-getting-started.md`

---

documentation/articles/wasm-getting-started.md

We should explicitly state that `swiftly` installation steps are required on macOS and clarify current lack of support on Windows hosts.

Clarify host platform specifics in `wasm-getting-started.md`

---

android-workgroup/index.md

The Android workgroup forum seems to have been moved from https://forums.swift.org/c/development/android to https://forums.swift.org/c/platform/android with no redirect (as pointed out at https://forums.swift.org/t/link-to-this-discussion-forum-is-broken-in-documentation/82336/2). This PR fixes the link.

Fix link to Android workgroup discussion forum

---

_info-architecture/0003-swift-docs-proposal.md

Extending the proposal details based on feedback from the Swift Core Team
- explicitly lists all files in /documentation from swift.org to identify a migration plan for it
- updates future directions to reflect DocC content now in the Swift GH repo for the compiler
- annotated some files within server guides that are known to be incomplete or inaccurate for removal and redirect only
- acknowledges swift/java interop as likely needing it's own location separate from Swift and C/C++ interop
- adds migration plans now that Swift also has a project-operations GH repository

updates the docs repository proposal

---

_data/contributer-experience-workgroup/members.yml

Sam join the group a few month ago but we didn't add him to the member list. This change aims to rectify it.
- Added new entry for Sam to `_data/contributer-experience-workgroup/members.yml`
The Contributor Experience Workgroup page would list Sam as a member now.

Add "Sam Khouri" to "Contributor Experience Workgroup"

---

_posts/2025-10-03-swift-profile-recorder.md

Fixes typo on Swift Profile Recorder blog post.
