swiftlang/swift-org-website

_data/builds/swift-5_6_1-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_6_1-release/amazonlinux2.yml, _data/builds/swift-5_6_1-release/centos7.yml, _data/builds/swift-5_6_1-release/ubuntu1804.yml, _data/builds/swift-5_6_1-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_6_1-release/ubuntu2004.yml, _data/builds/swift-5_6_1-release/windows10.yml, download/_older-releases.md, download/index.md
=> Swift 5.6.1 Release

_data/builds/swift-5_7-branch/amazonlinux2-aarch64.yml, _data/builds/swift-5_7-branch/amazonlinux2.yml, _data/builds/swift-5_7-branch/centos7.yml, _data/builds/swift-5_7-branch/ubuntu1804.yml, _data/builds/swift-5_7-branch/ubuntu2004-aarch64.yml, _data/builds/swift-5_7-branch/ubuntu2004.yml, _data/builds/swift-5_7-branch/xcode.yml, download/_older-5_7-snapshots.md, download/index.md
=> Support 5.7 dev snapshots

sswg/index.md
Updates SSWG's meeting time to reflect the time we currently meet.
Resolves #50
=> Update SSWG Meeting time

CODEOWNERS
update code owners to reflect workgroup members
=> update code owners to reflect workgroup members

docker-compose.yaml
motivaiton: run soundness on CI
changes: add docker task
=> add docker task to run the soundness script

docker-compose.yaml
In the future we can use `test` task for verifying changes.
=> Create test task for Docker compose

_data/authors.yml
Update author details for Kristina Fox and Holly Borla
Add Gravatar images and updated bios
=> Update author details

_posts/2022-07-14-vscode-extension.md
Update the timestamp on the VS Code extension blog post
Rename blog post file and edit the timestamp metadata
Timestamp accurately reflects blog post timing
=> Update timestamp on VS Code blog post

_posts/2022-07-22-documentation-workgroup.md, documentation-workgroup/index.md
Adds a blog post and a charter document for the new Documentation Workgroup!
=> Add Documentation Workgroup documents

community/_forums.md
=> Fix typos in _forums.md

documentation/index.md
swift.org invites links to translation projects to be added to the list:
> If you know of a quality translation project underway, please let us know
Added a single link to a website where Ukrainian translation of Swift documentation is hosted.
The list of documentation translation projects is extended.
=> Add link to Ukrainian translation of documentation

_data/authors.yml, _posts/2022-08-30-swift-nio-imap.md
Add the swift-nio-imap blog post
_data/authors.yml file was updated to add Daniel Eggert
Adds a blog post to swift.org
=> Add blog post on swift-nio-imap

download/_older-5_7-snapshots.md, download/index.md
=> [Download] Add Ubuntu 22.04 for Swift 5.7 snapshots

_data/builds/swift-5_6_3-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_6_3-release/amazonlinux2.yml, _data/builds/swift-5_6_3-release/centos7.yml, _data/builds/swift-5_6_3-release/ubuntu1804.yml, _data/builds/swift-5_6_3-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_6_3-release/ubuntu2004.yml, _data/builds/swift-5_6_3-release/windows10.yml, download/_older-releases.md, download/index.md
=> [Download] Release Swift 5.6.3

_data/builds/swift-5_7-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_7-release/amazonlinux2.yml, _data/builds/swift-5_7-release/centos7.yml, _data/builds/swift-5_7-release/ubuntu1804.yml, _data/builds/swift-5_7-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_7-release/ubuntu2004.yml, _data/builds/swift-5_7-release/ubuntu2204-aarch64.yml, _data/builds/swift-5_7-release/ubuntu2204.yml, _data/builds/swift-5_7-release/windows10.yml, download/_older-releases.md, download/index.md
=> [Download] Swift 5.7 Release

_posts/2022-09-06-swift-5.7-released.md, _posts/2022-09-12-swift-5.7-released.md
The content in this post has been gathered from various people who have contributed to Swift 5.7. All feedback is welcome!
=> Add draft of the Swift 5.7 release blog post.

_posts/2022-09-12-swift-5.7-released.md
Noticed this typo while reading the blog post. 
Side note: amazing work by the Swift team! Thanks for all you do.
=> Fix typo in 2022-09-12 Swift post

_data/sswg/projects.yml
Add the GraphQL projects as accepted SSWG projects
Review thread: https://forums.swift.org/t/sswg-0019-graphql-graphiti/59799/12
cc @0xTim @tomerd
=> [sswg] accepted GraphQL projects

_data/builds/swift-5_7_1-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_7_1-release/amazonlinux2.yml, _data/builds/swift-5_7_1-release/centos7.yml, _data/builds/swift-5_7_1-release/ubuntu1804.yml, _data/builds/swift-5_7_1-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_7_1-release/ubuntu2004.yml, _data/builds/swift-5_7_1-release/ubuntu2204-aarch64.yml, _data/builds/swift-5_7_1-release/ubuntu2204.yml, _data/builds/swift-5_7_1-release/windows10.yml, download/_older-releases.md, download/index.md
=> [Download] Swift 5.7.1 Release

community/index.md
=> Update the workgroups info in Community Structure area

_posts/2022-12-09-future-of-foundation.md
Add blog post about the Foundation announcement to be made at ServerSide.swift on 12/9/22
Community outreach about exciting Foundation plans
Add _posts/2022-12-09-future-of-foundation.md
New blog post
=> Foundation OSS blog

_data/builds/swift-5_7_2-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_7_2-release/amazonlinux2.yml, _data/builds/swift-5_7_2-release/centos7.yml, _data/builds/swift-5_7_2-release/ubuntu1804.yml, _data/builds/swift-5_7_2-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_7_2-release/ubuntu2004.yml, _data/builds/swift-5_7_2-release/ubuntu2204-aarch64.yml, _data/builds/swift-5_7_2-release/ubuntu2204.yml, _data/builds/swift-5_7_2-release/windows10.yml, download/_older-releases.md, download/index.md
=> [Release] Swift 5.7.2 on Download page

download/index.md
=> [Release] Swift 5.7.2 for Windows 10

download/_apple-platforms.md
https://github.com/apple/swift-org-website/issues/199
=> Update the steps to select toolchain in Xcode

download/_build-arch.html, download/_older-releases.md, download/_release_build.html, download/_release_build_arch.html
* Fix footnote numeration in release tables.
* Use numeric superscripts for footnotes consistently.
=> download: Revise footnotes

_layouts/base.html, server/index.md
- Document have a meta description (Now we have 100/100 points in Lighthouse scoring in SEO :) )
=> SEO improvement

_data/builds/swift-5_7_3-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_7_3-release/amazonlinux2.yml, _data/builds/swift-5_7_3-release/centos7.yml, _data/builds/swift-5_7_3-release/ubuntu1804.yml, _data/builds/swift-5_7_3-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_7_3-release/ubuntu2004.yml, _data/builds/swift-5_7_3-release/ubuntu2204-aarch64.yml, _data/builds/swift-5_7_3-release/ubuntu2204.yml, _data/builds/swift-5_7_3-release/windows10.yml, download/_older-releases.md, download/index.md
=> [Download] Release Swift 5.7.3

getting-started/_use-cases.md
Fix a misspelling of 'language'.
=> Fix a misspelling of 'language'

sswg/index.md
The proposal review of https://forums.swift.org/t/sswg-0021-swift-cassandra-client/62658 concluded and accepted the library
=> SSWG: Cassandra client is accepted

gsoc2023/index.md
A few initial project ideas while we still gather ideas and potential mentors, so that the page isn't completely empty while the application goes through :)
=> Add a few initial proposal ideas, more to come

gsoc2023/index.md
Two more proposals from the Swift team, focused on developer experience.
=> [GSoC 2023] Two more proposals

gsoc2023/index.md
We also remove one of the previously added projects after thinking through it some more.
=> GSoC 2023: Add memcached client project

CODEOWNERS
* _post -> _posts
* Update Mishal's info
=> Fix typo in the CODEOWNERS file

_data/builds/swift-5_8-release/amazonlinux2-aarch64.yml, _data/builds/swift-5_8-release/amazonlinux2.yml, _data/builds/swift-5_8-release/centos7.yml, _data/builds/swift-5_8-release/ubi9-aarch64.yml, _data/builds/swift-5_8-release/ubi9.yml, _data/builds/swift-5_8-release/ubuntu1804.yml, _data/builds/swift-5_8-release/ubuntu2004-aarch64.yml, _data/builds/swift-5_8-release/ubuntu2004.yml, _data/builds/swift-5_8-release/ubuntu2204-aarch64.yml, _data/builds/swift-5_8-release/ubuntu2204.yml, _data/builds/swift-5_8-release/windows10.yml, download/_older-releases.md, download/index.md
=> [Download] Swift 5.8 Release

documentation/index.md
Keep the Spanish translation updated with the correct URL.
Added the production URL to the website where the Spanish translation of Swift documentation is hosted.
The documentation's Spanish translation project is updated with the correct URL.
=> Update URL of Spanish translation site

documentation/cxx-interop/project-build-setup/index.md
=> Update build and status page

mentorship/index.md
This change is to update the 2023  mentorship timeline.
=> [Mentorship] Update the 2023 timeline

_data/authors.yml, _posts/2023-06-12-introducing-swift-openapi-generator.md
This PR is for an announcement blog post for Swift OpenAPI Generator.
=> Add blog post 'Introducing Swift OpenAPI Generator'

_data/authors.yml, _posts/2023-07-06-introducing-swift-http-types.md, _posts/2023-07-10-introducing-swift-http-types.md
Add announcement blog post for Swift HTTP Types
=> Add blog post "Introducing Swift HTTP Types"

community/index.md
=> Add forums link to contact the community groups

documentation/index.md
Swift.org recommends users inform the organization about new translation projects by reaching out to the Compiler Developer forums.
> If you know of a quality translation project underway, please let us know on the [Compiler Development](https://forums.swift.org/c/development/compiler) forums, and we’ll provide a link to that project on this page.
However, since the website is now open source, users should be advised to submit such information via a Pull Request.
Modified the paragraph to advise users to inform about new translation projects via submission of a Pull Request on this repository.
Users can simply submit a Pull Request to inform the Swift Organization about new translation projects so they can add a link.
=> Update instructions for new translation projects

_data/navigation.yml
=> Update navigation for install page

documentation/cxx-interop/project-build-setup/index.md
A missing comma found in the code block.
Add a missing comma.
Valid Swift code that can be copied and use directly.
=> Add missing comma

sswg-survey-2023/index.md
Prepare page for SSWG survey -- the link is currently paused and will just work when we decide to activate it.
=> Prepare SSWG survey page

_posts/2023-08-29-swift-5.9-released.md
* Add draft of the Windows section from Saleem.
* Add a draft of the introduction.
* Minor editorial pass based on PR feedback.
=> Updates to the 5.9 blog post draft.

_data/builds/swift_releases.yml
https://github.com/apple/swift-org-website/issues/391
=> Remove the duplicate of Swift 5.0 release in swift_releases.yml file

_data/builds/swift_releases.yml
=> Release Swift 5.9

_data/sswg/projects.yml
SSWG acceptance here: https://forums.swift.org/t/sswg-0022-sqlitenio/66548/3
add SQLite NIO to the project list
Up to date SSWG project list
=> Include sqlite-nio in sswg projects

_data/sswg/projects.yml
Add swift-service-context and swift-distributed-tracing to SSWG packages.
swift-service-context and swift-distributed-tracing have just been accepted as SSWG packages
Edited `_data/sswg/projects.yml`
=> Add SSWG packages service context and distributed tracing

server/guides/deploying/ubuntu.md
I was using the documentation for a project, and when I noticed a small spelling error, I thought I would suggest a minor correction 🫣
arifacts to artifacts
=> Update correction ubuntu.md

_data/builds/swift_releases.yml, download/_build-platform.html
=> [Download] Release Swift 5.9.1

_data/core_team_emeriti.yml, community/index.md
Display emeriti members of Swift core team.
=> Display core team emeriti.

assets/javascripts/swift-evolution.js
Add the upcoming feature flag for SE-0411 to the
evolution dashboard JavaScript.
=> Add Upcoming Feature Flag for SE-0411

_posts/2023-09-18-swift-5.9-released.md
<!— Fixes in the provided 'Parameter packs' code examples -->
<!— Corrected returned parameters -->
<!— The given examples seems more logical now -->
=> Parameter packs code examples fixes

_data/packages/packages.yml
This update contains the December data file with new packages for the Packages page.
Packages in the Community Showcase were nominated in [this thread on the Swift forums](https://forums.swift.org/t/nominations-for-the-packages-community-showcase-on-swift-org/68168) and were voted on by the [SWWG](https://www.swift.org/website-workgroup/).
=> December updates for the Packages page

_data/server-workgroup/projects.yml
The link is slightly off 😉
Correct the link.
Correct GitHub link to the package repository.
=> Fix DiscordBM link

_data/builds/swift_releases.yml
=> [Download] Swift 5.9.2 Release

assets/javascripts/swift-evolution.js
Add the upcoming feature flag for SE-0418 to the evolution dashboard JavaScript.
=> Add Upcoming Feature Flag for SE-0418

server/guides/deploying/heroku.md
Update to recent versions so newcomers can use examples from this guide directly without further changes. Additional context was added to make it easier to understand how Heroku works in general.
- update to latest Heroku stack
- change default branch name to `main`
- fix outdated/broken links
- consistent formatting & capitalization
- additional links and high-level overview
A hopefully easier-to-follow guide :)
=> Update and refine the Heroku deployment guide

server/guides/deploying/heroku.md
Minor follow-ups of #472 that were detected during testing.
=> Fix link fragments in Heroku deployment guide

_data/documentation.yaml
=> Fix typo in documentation

_data/server-workgroup/members.yml, _data/server-workgroup/projects.yml
- Adds MongoKitten as an incubated project
- Adds myself as a new member
=> SSWG projects and members update

_includes/navigation.html, install/index.md
=> Update the install page to include download link to nightly toolchains

contributor-experience-workgroup/index.md
=> Update the member for Contributor Experience Workgroup

gsoc2024/index.md
Add a GSoC '24 project: Lexical scopes for swift-syntax
=> GSoC project: Lexical scopes for swift-syntax

gsoc2024/index.md
Add a `etcd` client proposal for the 2024 GSOC projects.
=> [GSOC 2024] etcd client proposal

gsoc2024/index.md
=> GSoC 2024: Building Swift Macros with WebAssembly

_data/authors.yml, _posts/2024-02-20-mlx-swift.md
Add blog post highlighting the Swift bindings for MLX.
Adds the blog post and updates the authors.yml file.
A new blog post appears.
=> Add MLX Swift blog post

assets/javascripts/swift-evolution.js
Proposal SE-0423 has an upcoming feature flag. Adding it to the evolution script so it appears on the evolution dashboard.
=> Add upcoming feature flag for proposal SE-0423

_posts/2024-02-20-mlx-swift.md
Fix typo in example output for MLX blog post
Error-free documentation helps build trust, as users feel more confident in the information provided and in the expertise of the author or organization.
Changed output to reflect what should be actually returned.
Readers will not be confused when checking the example output against theirs.
=> Fix typo in example output

gsoc2024/index.md
Essentially, this is a paraphrased version of https://forums.swift.org/t/implementing-incremental-re-parsing-in-swiftparser-gsoc-2023/63291/2.
=> [GSoC] Add section with tips of how to get started writing a proposal

_data/builds/swift_releases.yml
Docker support will be available soon.
=> [Download] Swift 5.10 Release

_posts/2024-03-12-byte-sized-swift-tiny-games-playdate.md
=> update playdate post with link to forum post

_posts/2024-03-12-byte-sized-swift-tiny-games-playdate.md
Fix inline videos for chrome and Firefox users
=> update playdate post inline videos

_data/authors.yml, _posts/2024-03-28-sswg-update-2024.md
Fixes missing blogpost author entry
=> add joannis to authors.yaml

_data/server-workgroup/projects.yml
Acceptance thread https://forums.swift.org/t/sswg-0030-jwtkit/70598
=> Add JWTKit to SSWG vetted projects

_data/server-workgroup/projects.yml
Update JWTKit description
The package's description was lifted from the proposal and isn't particularly descriptive
Update the description
=> Update JWTKit description

_data/server-workgroup/projects.yml
Adds Oracle NIO as an incubated project
Review discussion : 
https://forums.swift.org/t/sswg-0028-oracle-nio/69502
Voted by the SSWG on 2/29/2024
=> add oracle NIO to the list of projects

getting-started/vapor-web-server/index.md
=> fix word: with –> within in the webserver starting guide

_data/server-workgroup/projects.yml
Adds a couple of new projects recently incubated by the SSWG
cc @adam-fowler
=> Add New Incubated Projects (May 2024)

platform-steering-group/index.md
Apply some editorial changes to the charter and minor tweaks about the processes (use of certain forums areas).
=> PSG: update the charter to the final version

_includes/install/_linux_platforms_tabs.md
Small proposal for changing the title here to be more concise and consistent, and I don't think we need to mention installing a "specific toolchain" here.
Updated the copy.
|Before|After|
|---|---|
|![](https://github.com/apple/swift-org-website/assets/35671299/ee2b194d-7549-46f8-9d24-27b60d9644af)|![](https://github.com/apple/swift-org-website/assets/35671299/cd50cc34-9021-4045-9bfe-3c0e68a57103)|
=> Improve Linux platform selection copy on install page

_data/builds/development/static_sdk.yml, _data/builds/swift-6_0-branch/static_sdk.yml, _includes/install/_build_snapshot.md, _includes/install/_static_sdk_dev.md, documentation/articles/static-linux-getting-started.md, install/macos/index.md
=> Add download links for the static SDK to install page

_data/authors.yml, documentation/articles/getting-started-with-vscode-swift.md
Fixes #704.
- Adds @matthewbastien and @plemarquand to the list of authors (please let me know if I want to add a description to your profiles as well!)
- Changed 2 links from absolute to relative (when on Swift.org, it's better to use relative links as they also will work in other environments, e.g. when running the website locally)
=> Improve Swift in VSCode getting started article

assets/stylesheets/_mobile.scss, assets/stylesheets/_screen.scss, contributor-experience-workgroup/index.md
On some pages, e.g. https://www.swift.org/documentation/concurrency/, the page scrolls horizontally due to some inline code blocks not breaking. This is not the best experience. Instead, it's better to wrap these code blocks into new lines.
- Make inline code blocks break and wrap into new lines instead of extending outside the viewport
- Remove inline code blocks from some links on https://www.swift.org/contributor-experience-workgroup/
- I originally intended to just fix these but then noticed the issue in more places, which is why I applied the site-wide fix instead. However, I decided to still remove these inline code blocks here to keep it consistent with the workgroup contact links in other places, e.g. on https://www.swift.org/website-workgroup/#communication
- Added hyphenation to …
=> Fix horizontal scroll on mobile on some pages

_data/server-workgroup/members.yml
The previous PR was mentioning @tib but actually forgot to include him :)
https://github.com/apple/swift-org-website/pull/717
=> SSWG: Add Tibor to the members list

_data/packages/packages.yml, _data/packages/showcase-history.yml
This pull request updates the automated rankings from the Swift Package Index that have happened this month.
This does not change the Community Showcase and there are no human-curated changes in this PR.
=> Packages page search ranking and compatibility updates.

documentation/server/index.md, sswg/incubated-packages.md, sswg/incubation-process.md, sswg/index.md
- alter server & sswg pages
- hide doc links from server documentation page 
- new sswg incubation-process page
=> Server related page updates

README.md
Enhance README.md for adding 'bash' to the code block.
=> Enhance README.md for adding 'bash' to the code block.

_data/builds/swift-6_0-branch/windows10-arm64.yml, _data/builds/swift-6_0-branch/windows10.yml, install/windows/index.md
=> [Install] Add Swift 6.0 nightly Windows 10 arm64 toolchain support

_data/packages/packages.yml, _data/packages/showcase-history.yml
This pull request updates the automated rankings from the Swift Package Index that have happened this month.
This does not change the Community Showcase and there are no human-curated changes in this PR.
=> Packages page search ranking and compatibility updates

documentation-workgroup/index.md
Updates the list of members in the documentation workgroup.
cc @swiftlang/documentation-workgroup @sofiaromorales
=> Update documentation workgroup members

documentation/articles/getting-started-with-vscode-swift.md
=> Fix spelling nit in VSCode instructions

_data/builds/swift_releases.yml, _includes/install/_static_sdk_release.md
=> [Release] Swift 6.0.1

_includes/install/_build_release.md, install/windows/index.md
Fix typo in response to https://x.com/__JoshuaJRoot__/status/1849723805167489172
Thanks for reporting!
=> Fix spelling error in Docker container pages

_includes/install/_linux_platforms_tabs.md, install/macos/index.md
This patch updates the download URL's to match the simple uname friendly URL's in #828
=> Adjust the URLs and instructions to support upcoming swiftly preview release

_data/server-workgroup/projects.yml
Was recently accepted to the SSWG incubation packages
=> Add ASN.1 package to incubating

documentation/server/guides/libraries/log-levels.md
More guidance was needed on whether libraries should mutate Logger's log level and log handler or not.
Clarify that libraries should not do that, with more context. Also removed language using "higher" and "lower" for log levels, as it's ambiguous, and replaced with "more severe" and "less severe".
Clearer documentation for Swift server library authors around logging.
=> [Server Guides] Logging clarifications

gsoc2025/index.md
Add some ideas for tutorials in the Swift VS Code extension. Also attempt to fix some minor typos that I noticed.
=> Add some more VS Code Extension ideas for GSoC 2025

.well-known/atproto-dtd
Add record to enable us to preserve Bluesky domain handle.
=> Add social verification record

_data/authors.yml, _posts/2025-03-28-introducing-swiftly_10.md
Introduces swiftly 1.0 in the form of a blog post.
=> Introducing swiftly 1.0

_data/builds/swift_releases.yml
Docker images will be available soon.
=> Swift 6.1 Release

_posts/2025-03-31-swift-6.1-released.md, _posts/2025-NN-NN-swift-6.1-released.md
Add a draft of the 6.1 release blog post.
=> Add 6.1 release blog post draft.

gsoc2025/index.md
Working on some additional guidance about GSoC proposals.
=> Improve guidance about GSoC proposals

_data/server-workgroup/members.yml
Add Josh Elkins in the list of SSWG members
Modified the `_data/server-workgroup/members.yml` 
This page should be updated 
https://www.swift.org/sswg/
=> [SSWG] Add Josh as SSWG member

ecosystem-steering-group/index.md
Fix a small grammatical issue on the Ecosystem Steering Group page.
Previously, the first part of the paragraph was left as an incomplete sentence.
Changed a period to a comma and modified the case of the following word accordingly.
The paragraph now consists of properly constructed sentences.
=> Fix small grammatical issue

_data/new-data/landing/callouts.yml
There is a typo and a copy correction
Copy has been changed
=> Update copy home

_data/new-data/install/linux/amazon-linux/amazon-linux-2/releases.yml, _data/new-data/install/linux/debian/debian-12/releases.yml, _data/new-data/install/linux/fedora/fedora-39/releases.yml, _data/new-data/install/linux/static-linux-sdk-dev.yml, _data/new-data/install/linux/ubi/ubi-9/releases.yml, _data/new-data/install/linux/ubuntu/ubuntu-20-04/releases.yml, _data/new-data/install/linux/ubuntu/ubuntu-22-04/releases.yml, _data/new-data/install/linux/ubuntu/ubuntu-24-04/releases.yml, _data/new-data/install/macos/releases.yml, _includes/new-includes/components/code-box.html, _includes/new-includes/components/linux-releases.html, assets/stylesheets/new-stylesheets/pages/_get-started.scss, assets/stylesheets/new-stylesheets/pages/_install.scss, install/macos/index.md
We need to reorganize the data of the install page
The template is more compact
=> Update Install data / design

mentorship/index.md
Also update links to the interest surveys for this year.
=> [markdown] Add timeline for 2025 Swift mentorship program

assets/stylesheets/new-stylesheets/_themes.scss, assets/stylesheets/new-stylesheets/pages/_get-started.scss
- Fix missing bg on codeblock
- Update dark mode landing background
=> Update BG Styles

_includes/new-includes/components/image-text-row.html, assets/stylesheets/new-stylesheets/pages/_get-started.scss
- Fix incorrect condition in template
- Fix headline line-height
- Update condition
- Add line height value
Component should better reflect spec
=> Fix: Image Text Row 

assets/stylesheets/new-stylesheets/_syntax.scss, assets/stylesheets/new-stylesheets/includes/callout/_base.scss, assets/stylesheets/new-stylesheets/pages/_get-started.scss, assets/stylesheets/new-stylesheets/pages/_index.scss, index.md
- Sub headlines are using various typography treatments. These should be consistent. 
- br tag is causing line break issue on small
Updated typography CSS.
Updated headline styles.
=> Typography Styles

404.md, assets/stylesheets/new-stylesheets/_pages.scss, assets/stylesheets/new-stylesheets/_themes.scss, assets/stylesheets/new-stylesheets/pages/_exception.scss
Currently the 404 page shows:
```
Not Found
The requested URL was not found on this server.
```
@shahmishal we need to add the redirect in the Server.
=> Add 404 page

404.md, 500.md
Currently the 404 page shows:
```
500 Internal Server Error
```
@shahmishal we need to add the redirect in the Server.
Now the page shows something like the 404 page
=> Add checkout page
